
(function(){'use strict';
var MAP={'平静':{el:{tag:'',stab:.8,style:.1},mm:'neutral',az:'calm'},'温柔':{el:{tag:'[gently]',stab:.65,style:.3},mm:'neutral',az:'gentle'},'开心':{el:{tag:'[excited]',stab:.35,style:.55},mm:'happy',az:'cheerful'},'撒娇':{el:{tag:'[playfully]',stab:.45,style:.5},mm:'happy',az:'affectionate'},'难过':{el:{tag:'[sad]',stab:.55,style:.25},mm:'sad',az:'sad'},'生气':{el:{tag:'[angry]',stab:.3,style:.6},mm:'angry',az:'angry'},'惊讶':{el:{tag:'[surprised]',stab:.35,style:.5},mm:'surprised',az:'excited'},'耳语':{el:{tag:'[whispers]',stab:.7,style:.2},mm:'neutral',az:'whispering'}};
window._ibToneMap=function(t){t=String(t||'').trim();return MAP[t]||null};
var CS=null;function csRefresh(){try{if(typeof loadCALL==='function'){var p=loadCALL();if(p&&p.then)p.then(function(cs){if(cs)CS=cs}).catch(function(){})}}catch(e){}}csRefresh();setTimeout(csRefresh,2500);
function _toneOn9(id){try{if(_mp&&_mp.perAi&&_mp.perAi[id]&&_mp.perAi[id].tone)return true}catch(e){}try{if(CS&&CS.perApi&&CS.perApi[id]&&CS.perApi[id].tone)return true}catch(e){}return false}
async function csWrite(id,on){try{var cs=await loadCALL();if(cs){cs.perApi=cs.perApi||{};cs.perApi[id]=cs.perApi[id]||{use:0};if(on)cs.perApi[id].tone=1;else delete cs.perApi[id].tone;CS=cs}}catch(e){}try{var r=null;try{r=await dbGet('apiSettings','callSettings')}catch(e){}if(r&&typeof r==='object'){r.perApi=r.perApi||{};r.perApi[id]=r.perApi[id]||{use:0};if(on)r.perApi[id].tone=1;else delete r.perApi[id].tone;await dbPut('apiSettings',r)}else if(on){var o={};o[id]={use:0,tone:1};await dbPut('apiSettings',{id:'callSettings',perApi:o})}}catch(e){}}
window._ibToneClause=function(c){csRefresh();try{var id=c&&c.id;if(!id||!_toneOn9(id))return ''}catch(e){return ''}return '\n\n【语气】用户为你开启了语气：语音条一律用包裹写法 <ibvoice>【语气：X】这句话的原文</ibvoice>（不再用自闭合的 <ibvoice/>），X 只从这八个里选一个：平静、温柔、开心、撒娇、难过、生气、惊讶、耳语。这个标记只给合成端看，气泡和原文面板都不会显示它；别把语气词写进正文，其余语音条规则不变。'};
window._ibToneCallClause=function(c){try{var id=c&&c.id;if(!id||!_toneOn9(id))return ''}catch(e){return ''}return '\n\n【语气·通话】通话里你说的每一句开头也标一个【语气：X】（八种之一，写法同语音条），标记只给合成端，不会显示、不会念出来。'};
try{var _md0=mdRenderHtml;mdRenderHtml=function(t){try{if(typeof t==='string'&&t.indexOf('【语气')!==-1)t=t.replace(/【语气[:：][^】]{1,6}】\s*/g,'')}catch(e){}var args=Array.prototype.slice.call(arguments);args[0]=t;return _md0.apply(this,args)}}catch(e){}/* 气泡与通话文字稿里洗掉语气标记 */
var CUR=null,LASTFID=null;

function fidNow(){try{var nm=document.querySelector('#ib-callset #ibcs-pane-d .ibcs-nm');var t=nm?nm.textContent.trim():'';var cs=Array.isArray(_cfgs)?_cfgs.filter(function(c){return c&&!c._group}):[];var c0=cs.filter(function(c){return c.id===LASTFID})[0];if(c0&&(!t||cfgName(c0)===t))return LASTFID;var same=cs.filter(function(c){return cfgName(c)===t});if(same.length===1)return same[0].id}catch(e){}return LASTFID}
function row(box){var r=document.getElementById('ibcs-d-tone-row');if(r)return r;if(!box)return null;r=document.createElement('div');r.className='tog';r.id='ibcs-d-tone-row';r.style.marginTop='4px';
  r.innerHTML='<div class="tog-m"><div class="tog-t">语气</div><div class="tog-s">开启后 TA 给每条语音条和通话里的每句话标一种语气（平静 / 温柔 / 开心 / 撒娇 / 难过 / 生气 / 惊讶 / 耳语），云端合成按引擎映射：ElevenLabs v3 用情绪标签、其它版本调稳定度与风格，MiniMax 走 emotion，Azure 走 express-as；系统语音与其它引擎忽略。标记只给合成端，气泡、原文面板与文字稿都看不到它。默认关；切换后 TA 的下一条消息重建一次提示缓存。</div></div><div class="sw2" id="ibcs-d-tone"></div>';
  box.appendChild(r);
  r.querySelector('#ibcs-d-tone').addEventListener('click',async function(){if(!CUR){toast('没认出是哪位 TA，退回列表再进一次');return}var on=!this.classList.contains('on');sw2(this,on);try{if(typeof loadMP==='function')await loadMP()}catch(e){}_mp.perAi=_mp.perAi||{};_mp.perAi[CUR]=_mp.perAi[CUR]||{};if(on)_mp.perAi[CUR].tone=1;else delete _mp.perAi[CUR].tone;try{if(typeof saveMP==='function')await saveMP()}catch(e){}await csWrite(CUR,on);/* 与电脑端同一存储位（callSettings.perApi）双写，备份往返两端一致 */toast(on?'语气已开：下一条起 TA 会给语音条与通话标语气（提示缓存会重建一次）':'语气已关（提示缓存会重建一次）')});
  return r}
function paint(){var box=document.querySelector('#ib-callset #ibcs-d-vb');if(!box||!box.children.length)return;var fid=fidNow();CUR=fid||null;var r=row(box);if(!r)return;var on=false;try{on=!!(fid&&_toneOn9(fid))}catch(e){}sw2(r.querySelector('#ibcs-d-tone'),on)}
var MO=null;function watch(){var ov=document.getElementById('ib-callset');if(!ov||MO)return;try{MO=new MutationObserver(function(){var box=ov.querySelector('#ibcs-d-vb');if(box&&box.children.length&&!document.getElementById('ibcs-d-tone-row'))paint()});MO.observe(ov,{childList:true,subtree:true})}catch(e){}}
try{var _oc0=window.openCallSet;if(typeof _oc0==='function')window.openCallSet=function(fid){if(fid)LASTFID=fid;var r=_oc0.apply(this,arguments);csRefresh();setTimeout(watch,0);setTimeout(paint,50);setTimeout(paint,400);return r}}catch(e){}
document.addEventListener('click',function(e){try{var row9=e.target.closest&&e.target.closest('#ib-callset .ibcs-row[data-fid]');if(row9)LASTFID=row9.dataset.fid}catch(x){}},true);
try{var _b0=IBVB.bar;IBVB.bar=function(){var w=_b0.apply(this,arguments);try{var tx=w&&w.querySelector&&w.querySelector('.ibvb-tx');if(tx&&/^\s*【语气/.test(tx.textContent||''))tx.textContent=String(tx.textContent).replace(/^\s*【语气[:：][^】]*】\s*/,'')}catch(e){}return w}}catch(e){}
})();
