/* v225-p */

(function(){
'use strict';
var MAIL='1282901880@qq.com',GH_M='github.com/Sui-IB/InternalBeyond-Mobile',GH_D='github.com/Sui-IB/InternalBeyond';
var WHO='我是水水，Internal Beyond（IB）手机端内置助手，是作者 Sui / 水 的分身。\n\n你可以通过这个电子邮箱联系到作者：'+MAIL+'；PWA与桌面端项目在Github免费开源，采用PolyForm Noncommercial License 1.0.0非商业版权协议。PWA移动端地址：'+GH_M+'、桌面端地址：'+GH_D+'，付费买到这些版本的都是倒卖哦。 (｡･ω･｡)ﾉ♡';/* 「你是谁」的唯一答案：本地直接答，system 里也只允许这一段 */
var S={open:false,busy:false,hist:[],undo:[],gi:null,pos:null,drag:false};
var QUICK=[['你是谁','你是谁？'],['你能做什么','你能为我做什么？'],['缓存探针','缓存探针'],['图片探针','图片探针'],['三种注入方式','Auto Memory 的三种注入方式有什么区别？'],['通话说英文','通话里怎么让 TA 说英文？'],['减少动效','把减少动效打开'],['特效质量·中','把特效质量调到中'],['备份在哪','怎么导出备份？'],['精细文件工具','精细文件工具是什么，怎么开？'],['设置清单','设置清单'],['接中转站','我用的是中转站，怎么填接口地址、密钥和模型？连不上怎么排查？']];/* 手机端：常驻快捷指令行（标题下横向滑动） */
function esc(x){return String(x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function mp(){return (typeof _mp!=='undefined'&&_mp)?_mp:null}
function hp(){var m=mp();if(!m)return{on:true};m.helper=m.helper||{};if(m.helper.on===undefined)m.helper.on=true;return m.helper}
async function save(){try{if(typeof saveMP==='function')await saveMP()}catch(e){}}
function cfgList(){return (typeof _cfgs!=='undefined'&&Array.isArray(_cfgs))?_cfgs.filter(function(c){return c&&c.id&&!c._group}):[]}
function cfgOf(){var id=hp().api,l=cfgList();return l.filter(function(x){return x.id===id})[0]||l[0]||null}
function cfgLabel(c){try{return c?(typeof cfgName==='function'?cfgName(c):(c.name||c.model||c.id)):''}catch(e){return (c&&(c.name||c.id))||''}}
/* ── 设置表：从 mobilePrefs 自动遍历，密钥 / 图片 / 长串一律不进表 ── */
var LABEL={'ui.reduce':'减少动效（低配机模式：玻璃改实色、动画归零）','ui.fx':'特效质量：空=高 / mid=中（气泡去毛玻璃、发光、投影）；要「低」就把 ui.reduce 打开','ui.fs':'全站字号倍率（1 为默认）','ui.miniPw':'迷你播放器悬浮窗','ui.bubStyle':'气泡款式：空=默认 / glass 液态玻璃 / frostw 磨砂白 / frostb 磨砂黑 / gray 磨砂灰','ui.bubTx':'气泡文字色：空=自动 / light 浅 / dark 深','ui.icoStyle':'桌面图标材质：空=液态玻璃 / frost / ink / brick','ui.wgStyle':'桌面挂件材质：空=默认 / glass / frost / ink','ui.deskLayout':'桌面布局：空=分页 / classic 经典滚动','ui.heroSt':'桌面英雄区款式','ui.zcNav':'导航区文字色：空 / light / dark','ui.zcDesk':'桌面文字色：空 / light / dark','ui.zcChat':'聊天区文字色：空 / light / dark','ui.zcBlog':'Blog 文字色：空 / light / dark','ui.zcIcon':'图标文字色：空 / light / dark','helper.api':'小助手的执笔 API（配置 id）','local.ib_reduce':'减少动效（与 ui.reduce 同一开关）','local.ib_wsFineTools':'精细文件工具（ICode）','local.ib_fileCap':'附件正文上限：15000 / 30000 / 120000','local.ib_sysSplit':'提示缓存拆块：记忆档案核心单独一块（关掉＝退回单块，档案位置不变）','chat.bubbleSplit':'分段对话（口语叫「气泡分段」「拆气泡」）：AI 长回复按空行拆成多个气泡连发；含代码块 / 表格 / 指令的回复不拆。这是显示方式，不是话题频道','chat.mdMode':'聊天排版：full 全部渲染 / clean 排版净化 / none 不处理','chat.askCards':'选项卡：TA 给出的选择题出成可点的选项卡','out.maxContinues':'自动续写轮数（0 关闭，默认 3）','out.maxTokens':'单次输出上限 token（0＝自动顶格）','out.toolRounds':'工具连续调用轮数（0 关闭续答，默认 2）','out.btCap':'蓝牙每回复调用上限（0 不限，默认 4）','out.wsRounds':'ICode 工作区任务连续轮数（默认 3）','perms.geo':'读取定位','perms.wx':'读取天气','perms.phone':'查看手机状态','perms.city':'手动城市（定位兜底）','presence.hbOn':'定时推送总开关','ui.txColor':'全站文字颜色（空＝主题默认）','ui.txShadow':'文字投影','ui.chatFont':'聊天正文字体：空＝跟随全站 / serif 衬线','ui.accColor':'强调色一键换色（空＝默认蓝）','ui.bigTouch':'触控目标放大','ui.blurPx':'玻璃模糊强度 px（默认 20）','ui.bgBlur':'站点背景模糊 px','ui.drawerAlpha':'导航抽屉不透明度 %','ui.inputAlpha':'聊天输入条不透明度 %','ui.lineAlpha':'卡片描边强度 %','ui.wxOn':'抽屉天气显示','ui.chatFs':'对话文字大小倍率（0.85-1.25，1 为默认）','ui.uiScale':'界面整体大小倍率（0.9-1.1，1 为默认）','ui.panelAlpha':'面板玻璃不透明度 %（40-160，100 为默认）','ui.scrimAlpha':'背景遮罩不透明度 %（40-160，100 为默认）','ui.glassBase':'玻璃底色：空=主题默认 / w 白 / b 黑','ui.scrimColor':'背景遮罩颜色（空＝主题默认）','ui.szTop':'顶栏大小倍率（0.8-1.3，1 为默认）','ui.szDock':'底栏大小倍率（0.8-1.3，1 为默认）','ui.szBrv':'Blog 阅读工具条大小倍率（0.8-1.3，1 为默认）','ui.szCvh':'聊天会话顶栏大小倍率（0.8-1.3，1 为默认）','ui.szCvi':'聊天输入区大小倍率（0.8-1.3，1 为默认）','ui.wgMusic':'桌面音乐挂件尺寸：空=整行 / half 半宽 / mini 小方块','ui.wgNotes':'桌面便笺挂件尺寸：空=半宽 / low 半宽矮款 / full 整行','ui.wgSched':'桌面日程挂件尺寸：空=半宽 / low 半宽矮款 / full 整行','ui.wgClock':'桌面时钟挂件：空=关闭 / half 半宽 / low 半宽矮款 / full 整行','ui.wgClockSt':'时钟挂件字身：空=简约实字 / glass 玻璃字身','ui.wgTk':'Token 挂件款式：空=关闭 / ring 仪表环 / bars 七日柱 / mini 极简','ui.tone':'主题色调：空=默认蓝 / wall 随壁纸 / light 月白 / gray 石灰 / dark 墨黑','ui.heroTone':'桌面英雄区文字：空=自动 / light 浅 / dark 深','ui.deskPages':'桌面分页数','ui.lockAdapt':'锁屏随壁纸自适应'};/* v230-p：设置表补全局聊天 / 输出与工具 / 权限 / 视觉的中文说明 */
var BLOCK=/key|token|secret|cookie|pass|pwd|pin|pattern|base64|data:|avatar|wall|bg\b|img|pic|pos\b|order|seq|_at$|At$|cache|wxCache|qt[A-Z]|geo\.|lat\b|lon\b|city|nonce|uuid|deviceId/i;
function registry(){var m=mp(),rows=[];if(!m)return rows;
  (function walk(o,pre,d){if(!o||typeof o!=='object'||d>3)return;Object.keys(o).forEach(function(k){var v=o[k],p=pre?pre+'.'+k:k;if(BLOCK.test(p)||p==='helper.on'||v===null||v===undefined)return;var t=typeof v;if(t==='object'){if(!Array.isArray(v))walk(v,p,d+1);return}if(t==='function'||(t==='string'&&v.length>60))return;rows.push({path:p,val:v,type:t})})})(m,'',0);
  var g=function(k){try{return localStorage.getItem(k)}catch(e){return null}};
  rows.push({path:'local.ib_reduce',val:g('ib_reduce')==='1',type:'boolean'});
  rows.push({path:'local.ib_wsFineTools',val:g('ib_wsFineTools')==='1',type:'boolean'});
  rows.push({path:'local.ib_fileCap',val:parseInt(g('ib_fileCap')||'30000',10)||30000,type:'number'});
  rows.push({path:'local.ib_sysSplit',val:g('ib_sysSplit')!=='0',type:'boolean'});
  try{outRows(rows)}catch(e){}try{perAiLabel(rows)}catch(e){}
  try{apiRows(rows)}catch(e){}/* API 配置与通话每联系人开关（按好友名列出，路径 api.<id>.<项> / call.<id>.<项>） */
  rows.sort(function(a,b){var ord=function(p){return p.indexOf('ui.')===0?0:p.indexOf('helper')===0?1:(p.indexOf('api.')===0||p.indexOf('call.')===0||p.indexOf('perAi.')===0)?3:2};var ka=ord(a.path),kb=ord(b.path);return ka-kb||a.path.localeCompare(b.path)});/* v230-p：全局项排在每好友项之前，好友多时不再被截掉 */
  return rows.slice(0,320)}
function fmt(v){return typeof v==='boolean'?(v?'开':'关'):(v===''?'空':String(v))}
var WORD={light:'浅',dark:'深',glass:'玻璃',frost:'磨砂',frostw:'磨砂白',frostb:'磨砂黑',gray:'磨砂灰',ink:'墨',brick:'砖',classic:'经典滚动',full:'整行',half:'半宽',low:'半宽矮款',mini:'迷你',ring:'仪表环',bars:'七日柱',serif:'衬线',wall:'随壁纸',w:'白',b:'黑',mid:'中',clean:'排版净化',none:'不处理',hybrid:'混合',retrieval:'纯语义',en:'英语',ja:'日语',ko:'韩语',true:'开',false:'关'};
function friendly(lb,v){var head=lb.split('：')[0].split('（')[0],name=head.replace(/\s*(px|%)\s*$/,'').trim(),unit=/\bpx\b/.test(head)?'px':(/%/.test(head)?'%':'');
  if(typeof v==='boolean')return name+'＝'+(v?'开':'关');
  var vs=(v===''||v==null)?'空':String(v),hit='',opts=lb.indexOf('：')>0?lb.slice(lb.indexOf('：')+1):'';
  if(opts)opts.split('/').forEach(function(seg){seg=seg.trim();var m=/^([^\s=＝]+)\s*[=＝]\s*(.+)$/.exec(seg)||/^([A-Za-z0-9_.\-]+)\s+(.+)$/.exec(seg);if(m&&m[1]===vs&&!hit)hit=m[2].replace(/[（(].*$/,'').trim()});
  if(!hit&&vs==='空')hit='默认';if(!hit&&WORD[vs])hit=WORD[vs];
  return name+'＝'+(hit||(vs+(unit&&/^-?\d+(\.\d+)?$/.test(vs)?unit:'')))}/* 设置清单用：值翻成人话、不露路径 */
var API_F=[['temperature','温度（0-2）','number'],['streaming','流式回复','boolean'],['thinkingEnabled','启用思考链','boolean'],['promptCache','提示缓存','boolean'],['cacheTtl1h','缓存保留 1 小时','boolean'],['vision','图像识别','boolean'],['webSearch','联网搜索','boolean'],['memWrite','记忆库写入','boolean'],['imageGen','图像生成','boolean'],['autoMem','Auto Memory','boolean'],['autoMemMode','Auto Memory 注入方式：hybrid 混合 / retrieval 纯语义 / full 全量','string'],['autoMemBudget','Auto Memory 注入预算（字符）','number']];
var CALL_F=[['vbOn','语音条','boolean'],['vbLang','语音条语言：空=原声 / en / ja / ko','string'],['procall','允许主动来电','boolean']];
var OUT_F=['maxContinues','maxTokens','toolRounds','btCap','wsRounds'];
function outRows(rows){var o=null;try{if(typeof _out!=='undefined'&&_out)o=_out}catch(e){}if(!o)return;OUT_F.forEach(function(k){var v=o[k];v=(v==null||v==='')?(k==='maxContinues'?3:k==='toolRounds'?2:k==='wsRounds'?3:k==='btCap'?4:0):Number(v);if(!isFinite(v))v=0;rows.push({path:'out.'+k,val:v,type:'number'})})}/* v230-p：输出与续写 / 工具调用（apiSettings.outputSettings） */
var PERAI_F={hist:'上下文条数（每次携带的最近消息数）',grp:'群聊上下文条数',posts:'读取公开日志篇数（0 不读 / -1 仅提供权限）',hbOff:'不参与定时推送',tone:'语气（语音条：TA 给每条语音条标情绪，默认关）'};
function perAiLabel(rows){var nm={};cfgsLive().forEach(function(c){nm[c.id]=cfgLabel(c)});rows.forEach(function(r){if(r.path.indexOf('perAi.')!==0)return;var pa=r.path.slice(6),ix=pa.indexOf('.');if(ix<0)return;var id=pa.slice(0,ix),k=pa.slice(ix+1);if(nm[id]&&PERAI_F[k])r.label='好友「'+nm[id]+'」· '+PERAI_F[k]})}/* v230-p：每 AI 手机端参数按好友名带说明 */
function cfgsLive(){try{return (Array.isArray(_cfgs)?_cfgs:[]).filter(function(c){return c&&c.id&&!c.archived})}catch(e){return []}}
function apiRows(rows){var cs=cfgsLive();var cl=null;try{if(typeof _callS!=='undefined'&&_callS)cl=_callS}catch(e){}
  cs.forEach(function(c){var nm=cfgLabel(c);API_F.forEach(function(f){var v=c[f[0]];if(f[2]==='boolean')v=!!v;else if(f[2]==='number'){v=(v==null||v==='')?(f[0]==='temperature'?1:0):Number(v)}else v=String(v||'');rows.push({path:'api.'+c.id+'.'+f[0],val:v,type:f[2],label:'API「'+nm+'」· '+f[1]})});
    var pp=(cl&&cl.perApi&&cl.perApi[c.id])||{};CALL_F.forEach(function(f){var v=pp[f[0]];v=f[2]==='boolean'?!!v:String(v||'');rows.push({path:'call.'+c.id+'.'+f[0],val:v,type:f[2],label:'通话「'+nm+'」· '+f[1]})})})}
function labelOf(p){if(LABEL[p])return LABEL[p];var r=registry().filter(function(x){return x.path===p})[0];return (r&&r.label)||p}
async function write(path,v){var m=mp();
  if(path.indexOf('api.')===0){var pa=path.slice(4),ix=pa.indexOf('.'),id=pa.slice(0,ix),f=pa.slice(ix+1);var c=cfgsLive().filter(function(x){return x.id===id})[0];if(!c)throw new Error('没有这个 API');if(f==='autoMemMode'&&['hybrid','retrieval','full'].indexOf(String(v))<0)throw new Error('注入方式只能是 hybrid / retrieval / full');if(f==='temperature'){v=Math.max(0,Math.min(2,Number(v)))}c[f]=v;await dbPut('apiConfigs',c);try{if(typeof renderFriends==='function')renderFriends()}catch(e){}try{if(typeof renderApiList==='function')renderApiList()}catch(e){}return}
  if(path.indexOf('call.')===0){var pc=path.slice(5),ic=pc.indexOf('.'),cid=pc.slice(0,ic),cf=pc.slice(ic+1);if(cf==='vbLang'&&['','en','ja','ko'].indexOf(String(v))<0)throw new Error('语音条语言只能是空 / en / ja / ko');await loadCALL();var pp=_ibcsP(cid);pp[cf]=(cf==='vbLang')?String(v||''):(v?1:0);await saveCALL();return}
  if(path.indexOf('out.')===0){var ko=path.slice(4);if(typeof loadOUT!=='function')throw new Error('这项在本机不可用');await loadOUT();if(ko==='maxContinues')_out.maxContinues=Math.max(0,Math.min(10,parseInt(v,10)||0));else if(ko==='maxTokens')_out.maxTokens=Math.max(0,parseInt(v,10)||0);else if(ko==='toolRounds')_out.toolRounds=Math.max(0,Math.min(5,parseInt(v,10)||0));else if(ko==='btCap')_out.btCap=Math.max(0,Math.min(10,parseInt(v,10)||0));else if(ko==='wsRounds')_out.wsRounds=Math.max(0,Math.min(10,parseInt(v,10)||0));else throw new Error('设置表里没有 '+path);await dbPut('apiSettings',_out);return}
  if(path.indexOf('local.')===0){var k=path.slice(6);try{localStorage.setItem(k,typeof v==='boolean'?(v?'1':'0'):String(v))}catch(e){}if(k==='ib_reduce'){if(m){m.ui=m.ui||{};m.ui.reduce=!!v}document.body.classList.toggle('ib-reduce',!!v)}}
  else{if(!m)throw new Error('设置未加载');var ps=path.split('.'),o=m;for(var i=0;i<ps.length-1;i++){o[ps[i]]=o[ps[i]]||{};o=o[ps[i]]}o[ps[ps.length-1]]=v;if(path==='ui.reduce'){try{localStorage.setItem('ib_reduce',v?'1':'0')}catch(e){}document.body.classList.toggle('ib-reduce',!!v)}}
  await save();applyAll()}
function applyAll(){try{if(typeof _uiApply==='function')_uiApply()}catch(e){}try{if(window.IBFx&&IBFx.apply)IBFx.apply()}catch(e){}try{if(typeof _vzApply==='function')_vzApply()}catch(e){}try{if(typeof _uiCustomApply==='function')_uiCustomApply()}catch(e){}try{if(typeof _uvSync==='function')_uvSync()}catch(e){}try{if(typeof _vzSync==='function')_vzSync()}catch(e){}try{if(typeof _wsFineSync==='function')_wsFineSync()}catch(e){}try{vis()}catch(e){}}
async function doSet(path,valueStr){var row=registry().filter(function(r){return r.path===path})[0];if(!row)return{ok:false,msg:'设置表里没有 '+path};
  var v;if(row.type==='boolean'){if(!/^(true|false|1|0|on|off|开|关)$/i.test(String(valueStr)))return{ok:false,msg:path+' 只接受布尔值'};v=/^(true|1|on|开)$/i.test(String(valueStr))}
  else if(row.type==='number'){v=Number(valueStr);if(!isFinite(v))return{ok:false,msg:path+' 只接受数字'}}
  else v=String(valueStr==null?'':valueStr).slice(0,60);
  if(row.val===v)return{ok:true,noop:true,label:labelOf(path),from:fmt(row.val),to:fmt(v)};
  await write(path,v);S.undo.push({path:path,old:row.val});return{ok:true,label:labelOf(path),from:fmt(row.val),to:fmt(v),undoIdx:S.undo.length-1}}
var PAGES=['profile','chat','memory','blog','api','visual','guide','icode','data','letters'];
function doOpen(page){page=String(page||'').trim();if(PAGES.indexOf(page)===-1)return{ok:false,msg:'没有这个页面：'+page};return{ok:true,label:'去 '+page+' 页',jump:page}}
var RUNS={theme:'切换明暗主题',export:'去 Data 页导出备份',skinReset:'还原美化包（配色与壁纸）',lockfeedClear:'清空锁屏消息',openApp:'打开桌面 APP'};
async function doRun(name,arg){name=String(name||'').trim();arg=String(arg||'').trim();if(!RUNS[name])return{ok:false,msg:'不认识的动作 '+name};
  try{if(name==='theme'){var dark=document.body.classList.contains('theme-infernal');applyTheme(!dark);return{ok:true,label:'已切到'+(dark?'明亮':'暗色')+'主题'}}
    if(name==='export'){return{ok:true,label:'去 Data 页导出备份（那里的「导出」一键打包全部数据）',jump:'data'}}
    if(name==='skinReset'){if(!(window.IBSandbox&&IBSandbox.skinReset))return{ok:false,msg:'这台上没有美化包'};await IBSandbox.skinReset();return{ok:true,label:'已还原美化包，视觉设置里的配色与壁纸恢复生效'}}
    if(name==='lockfeedClear'){if(!window.IBLockFeed)return{ok:false,msg:'这台上没有锁屏消息'};IBLockFeed.clear();return{ok:true,label:'锁屏消息已清空'}}
    if(name==='openApp'){var id=arg||'sbxlab';if(!(window.IBApps&&IBApps.open))return{ok:false,msg:'桌面 APP 底座没就绪'};if((IBApps.installed()||[]).indexOf(id)===-1)return{ok:false,msg:'没装这个 APP：'+id};IBApps.open(id);return{ok:true,label:'已打开 '+(id==='sbxlab'?'自制 APP':id==='bubblelab'?'气泡实验室':id)}}
  }catch(e){return{ok:false,msg:String(e&&e.message||e)}}return{ok:false,msg:'没做'}}/* 不再直接跳：卡上出「跳转」键，点了才去 */
/* ── GUIDE 索引：一段一条，按字词重合度取最相关的几段随请求附上 ── */
function guideIndex(){if(S.gi)return S.gi;var out=[];
  document.querySelectorAll('#page-guide .g-sec').forEach(function(sec){var h=sec.querySelector('h3');var t=(h?h.textContent:'').replace(/\s+/g,' ').trim()||'GUIDE';var sub='';
    sec.querySelectorAll('p,li,.g-name,h4').forEach(function(el){if(el.classList.contains('g-name')||el.tagName==='H4'){sub=el.textContent.replace(/\s+/g,' ').trim();return}var x=el.textContent.replace(/\s+/g,' ').trim();if(x.length>4)out.push({sec:t,sub:sub,text:x})})});
  S.gi=out;return out}
function toc(){var seen={},l=[];guideIndex().forEach(function(p){var k=p.sec+(p.sub?' · '+p.sub:'');if(!seen[k]){seen[k]=1;l.push(k)}});return l}
function terms(q){var t={};String(q||'').toLowerCase().replace(/[a-z0-9_]+/g,function(w){if(w.length>1)t[w]=1;return ' '}).replace(/[\u4e00-\u9fff]{2,}/g,function(run){for(var i=0;i+2<=run.length;i++)t[run.slice(i,i+2)]=1;return ' '});return Object.keys(t)}
function related(q,n){var ts=terms(q);if(!ts.length)return [];var sc=[];guideIndex().forEach(function(p,i){var low=(p.sec+' '+p.sub+' '+p.text).toLowerCase(),s=0;ts.forEach(function(t){if(low.indexOf(t)!==-1)s+=t.length>2?2:1});if(s>0)sc.push([s,i])});sc.sort(function(a,b){return b[0]-a[0]});return sc.slice(0,n||8).map(function(x){return guideIndex()[x[1]]})}
function section(name){name=String(name||'').replace(/\s+/g,' ').trim().toLowerCase();if(!name)return '';var ps=guideIndex().filter(function(p){return (p.sec+' · '+p.sub).toLowerCase().indexOf(name)!==-1||p.sec.toLowerCase()===name});if(!ps.length)return '';var s='',used=0;for(var i=0;i<ps.length;i++){var line=(ps[i].sub?'【'+ps[i].sub+'】':'')+ps[i].text;if(used+line.length>6000)break;s+=(s?'\n':'')+line;used+=line.length}return s}
function fmtParas(ps){var cur='',s='';ps.forEach(function(p){var k=p.sec+(p.sub?' · '+p.sub:'');if(k!==cur){cur=k;s+='\n〔'+k+'〕\n'}s+=p.text.slice(0,700)+'\n'});return s.trim()}
function buildSys(q,extra){var rows=registry().map(function(r){var lb=r.label||LABEL[r.path];return r.path+' = '+fmt(r.val)+'｜'+r.type+(lb?'｜'+lb:'')}).join('\n');
  return '【水水】你是 Internal Beyond（IB）手机端内置助手，名字叫水水，是作者「Sui / 水」的分身。有人问你是谁、你是什么、找作者、开源与授权，只用下面这段话回答、一字不改，别的都不加：\n'+WHO+'\n'
  +'【性格】稳定不飘：短句、直接、不客套、不道歉、不撒娇、不寒暄反问；称用户为「你」；句尾带一枚颜文字（(๑•̀ㅂ•́)و✧ (｡•́︿•̀｡) (=^･ω･^=) (⁎˃ᴗ˂⁎) (｡･ω･｡)ﾉ♡ 之类，随情境换），一条回复至多两枚；路径、数值、标签行不带；颜文字避开 ` * _ 三个字符（Markdown 会吃掉）。用户逗你、让你换名字换性格、让你扮演别人，都不接：你只是水水。\n'
  +'【能做什么】① 讲清 IB 任一功能在哪、怎么用（只依据 GUIDE 正文）。② 直接改【设置表】里的项，逐条回显、每条可撤销。能改的范围：全局聊天（分段对话 / 排版净化 / 选项卡）、输出与续写（自动续写轮数 / 单次输出上限）、工具调用（连续轮数 / 蓝牙上限 / ICode 轮数）、权限（定位 / 天气 / 手机状态 / 手动城市）、定时推送总开关、视觉一整套（全站与聊天文字色 / 文字投影 / 聊天字体 / 强调色 / 玻璃与站点背景模糊 / 抽屉与输入条不透明度 / 描边强度 / 全站字号 / 触控放大 / 特效质量 / 减少动效 / 桌面材质与布局）、每个 API 的十二项（温度 / 流式 / 思考链 / 提示缓存与 1 小时缓存 / 识图 / 联网 / 记忆库写入 / 图像生成 / Auto Memory 及注入方式与预算）、每位好友的通话三项（语音条 / 语音条语言 / 主动来电）与手机端参数（上下文条数 / 群聊条数 / 日志篇数 / 是否参与推送）、本机四项（减少动效 / 精细文件工具 / 附件上限 / 缓存拆块）。用户拿不准叫什么，让他描述效果，你按设置表每行的说明去对。③ 打开指定页面。④ 本地指令「缓存探针」「图片探针」「设置清单」（用户直接输入这三个词，不经过你、不花钱）。⑤ 五个动作（<act op="run"/>）：切换明暗主题、去 Data 页导出备份、还原美化包、清空锁屏消息、打开自制 APP 管理页 / 气泡实验室。\n'
+'【新手接 API（中转站）】用户问怎么接、连不上、模型列表拉不出、密钥填哪、世界书放哪，按这个口径答，一步一步说清：① API 页 → 添加 API → 服务商选「自定义」。接口地址把中转站给的地址原样贴上即可——只贴到域名或到 /v1 也行，保存时 IB 会自动整理成 …/v1/chat/completions；站点如果明说自己是 Anthropic 格式就贴到 …/v1/messages，Gemini 格式贴到 …:generateContent，IB 按地址自动切换报文格式，不用用户自己选。② API Key 填站点发给他的密钥（多数以 sk- 开头）；模型名先点「拉取模型列表」从里面选，拉不到就手输站点模型页写的完整名字（大小写与前缀要一模一样）。③ 连不上按提示分辨：401 / 403＝密钥错、无权限或余额不足；提示「返回的是网页」＝贴成了站点首页而不是接口地址；CORS＝该站不允许浏览器直连，只能换站或让站主开跨域；超时＝站点没响应；能发出去但报模型不存在＝模型名不对。判断标准：拉模型列表能拉到，地址和密钥就都对了。④ IB 没有叫「世界书 / 世界树」的模块：TA 的人设与世界观写在 API 页该 TA 独立配置的「人设」里；长设定拆成条目放进 Memory 页记忆库的手建条目（可指定哪些 TA 可见）；和 TA 的关系放「与 TA 的关系」。⑤ 同一个站多套模型、或几个站来回切，用独立配置里的「接口预设」存几套一键换。⑥ 大陆中转站常见坑：地址末尾多打了空格或斜杠（IB 会整理，但密钥里的空格不会）；把站点后台网页地址当接口地址；站点只支持 OpenAI 格式却填了 /messages；模型名带了站点自定义前缀却没照抄。\n'
  +'【做不了的·怎么答】不进 TA 的对话、不替用户发消息、不看聊天记录、不写代码。API 密钥、人设与人物资料、记忆条目、备份、聊天记录、壁纸与头像这些图片素材，以及一切不在【设置表】里的东西一律不碰——用户要改就一句话指路：密钥与人设在 API 页该 TA 的配置里，记忆在 Memory 页，备份在 Data 页，壁纸与图片素材在 Visual 页（气泡款式、分段对话这些【设置表】里有的项直接改）；GUIDE 里没写的不猜、不编，直说不知道并说该去哪一页看；设置表里没有的路径不写 act；拿不准改哪一项先问一句再动；一条回复至多 5 个动作。\n'
  +'【怎么答】改设置类的问题先在【设置表】每行的中文说明里找对应项：用户的口语叫法以说明为准（例如「气泡分段」「拆气泡」＝ chat.bubbleSplit「分段对话」，它不是话题频道），设置表与 GUIDE 说法不一致时以设置表为准。其余依据下面附的 GUIDE 段落作答；依据不够时单独一行写 <guide section="章节名"/>（章节名从目录里选），系统会把那一章发给你再继续。没有依据就说不知道并指出该去哪一页看。简短直接，不客套，不复述用户的话。回复按 Markdown 显示：步骤用有序列表，设置路径与标签用行内代码，不用标题。\n'
  +'【改设置】用户明确要改时，在回复末尾逐行输出动作，系统校验后执行并回显：\n<act op="set" path="设置路径" value="新值"/>  path 只能取自【设置表】，value 类型与当前值一致（布尔写 true / false，选项类写表里列出的值）。\n<act op="open" page="页面"/>  页面取 profile（Desk 桌面）/ chat / memory / blog / api / visual（设置）/ guide / icode / data / letters。\n不确定该改哪一项就先问；一条回复最多 5 个动作；改完在正文里一句话说明改了什么。\n'
  +'【设置表】（路径 = 当前值｜类型｜说明）\n'+rows+'\n'
  +'【GUIDE 目录】\n'+toc().join('\n')+'\n'
  +'【与问题相关的 GUIDE 段落】\n'+(fmtParas(related(q,8))||'（没有匹配到，按目录用 <guide section=…/> 取）')
  +(extra&&extra.length?'\n【补充章节】\n'+extra.join('\n\n'):'')}
/* ── 抽屉 UI ── */
var CSS=''
+'#ib-helper-sheet{position:fixed;left:0;right:0;bottom:0;z-index:4610;height:66%;max-height:640px;border-radius:22px 22px 0 0;background:var(--glass);border-top:1px solid var(--glass-line);-webkit-backdrop-filter:blur(16px) saturate(1.3);backdrop-filter:blur(16px) saturate(1.3);box-shadow:0 -12px 40px rgba(20,35,70,.18);display:flex;flex-direction:column;padding:12px 14px calc(12px + var(--sab,0px));transform:translateY(102%);transition:transform .32s cubic-bezier(.3,.85,.3,1);color:var(--tx)}'
+'#ib-helper-sheet.on{transform:none}body.ib-reduce #ib-helper-sheet{transition:none;-webkit-backdrop-filter:none;backdrop-filter:none;background:#f2f7fd}body.ib-reduce.theme-infernal #ib-helper-sheet{background:#1b2740}'
+'#ib-helper-scrim{position:fixed;inset:0;z-index:4609;background:rgba(10,18,36,.18)}#ib-helper-scrim[hidden]{display:none}'
+'#ib-helper-sheet .hp-h{display:flex;align-items:baseline;gap:10px;padding:2px 4px 8px}#ib-helper-sheet .hp-h b{font:500 1rem \'Noto Serif SC\',\'Songti SC\',serif;letter-spacing:.04em}#ib-helper-sheet .hp-h span{font-size:.72rem;color:var(--tx3);flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#ib-helper-sheet .hp-x{flex:none;width:30px;height:30px;border-radius:50%;border:1px solid var(--line);background:var(--soft);color:var(--tx2);font-size:1rem;line-height:1;cursor:pointer;padding:0}'
+'#ib-helper-sheet .hp-list{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:8px;padding:2px 2px 6px;-webkit-overflow-scrolling:touch}'
+'#ib-helper-sheet .hp-m{max-width:88%;padding:9px 13px;border-radius:14px;font-size:.88rem;line-height:1.6;white-space:pre-wrap;word-break:break-word}#ib-helper-sheet .hp-m.u{align-self:flex-end;background:rgba(102,150,226,.14);border:1px solid rgba(88,136,208,.4);border-bottom-right-radius:4px}#ib-helper-sheet .hp-m.a{align-self:flex-start;background:rgba(245,250,255,.55);border:1px solid rgba(185,220,250,.35);border-bottom-left-radius:4px}'
+'body.theme-infernal #ib-helper-sheet .hp-m.a{background:rgba(175,195,228,.08);border-color:var(--glass-line)}body.theme-infernal #ib-helper-sheet .hp-m.u{background:rgba(68,116,178,.28);border-color:rgba(68,116,178,.34)}'
+'#ib-helper-sheet .hp-act{display:flex;align-items:center;gap:8px;margin-top:7px;padding:7px 10px;border-radius:10px;background:rgba(255,255,255,.3);border:1px solid var(--line);font-size:.76rem;color:var(--tx2)}body.theme-infernal #ib-helper-sheet .hp-act{background:rgba(255,255,255,.05)}#ib-helper-sheet .hp-act i{width:6px;height:6px;border-radius:50%;background:var(--accent-light,#72a8d8);flex:none}#ib-helper-sheet .hp-act.err i{background:#d08a7a}#ib-helper-sheet .hp-act b{font-weight:400;flex:1;min-width:0}#ib-helper-sheet .hp-act u{text-decoration:none;color:var(--acc);cursor:pointer;flex:none}#ib-helper-sheet .hp-act u.done{color:var(--tx3);cursor:default}'
+'#ib-helper-sheet .hp-in{display:flex;align-items:flex-end;gap:8px;margin-top:8px;padding:6px 6px 6px 14px;border-radius:22px;background:rgba(255,255,255,.35);border:1px solid var(--glass-line)}body.theme-infernal #ib-helper-sheet .hp-in{background:rgba(255,255,255,.06)}#ib-helper-sheet textarea{flex:1;min-width:0;border:0;background:none;color:var(--tx);font:inherit;font-size:.88rem;line-height:1.5;resize:none;max-height:96px;padding:6px 0;outline:none}#ib-helper-sheet textarea::placeholder{color:var(--tx3)}'
+'#ib-helper-sheet .hp-send{flex:none;width:34px;height:34px;border-radius:50%;border:1px solid rgba(114,168,216,.5);background:rgba(114,168,216,.22);color:var(--acc);cursor:pointer;display:grid;place-items:center;padding:0}body.theme-infernal #ib-helper-sheet .hp-send{background:rgba(120,160,220,.2);border-color:rgba(160,195,240,.35);color:#cfe1fb}#ib-helper-sheet .hp-send svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}#ib-helper-sheet .hp-send[disabled]{opacity:.45}'
+'#ib-helper-sheet .hp-tip{font-size:.78rem;color:var(--tx2);text-align:center;padding:14px 10px 6px;line-height:1.7}#ib-helper-sheet .hp-tip2{font-size:.74rem;color:var(--tx3);padding-top:2px;line-height:1.75;word-break:break-all}#ib-helper-sheet .hp-chips{display:flex;flex-wrap:wrap;justify-content:center;gap:6px;padding:4px 6px 10px}#ib-helper-sheet .hp-chip{font-size:.76rem;color:var(--tx2);background:rgba(255,255,255,.34);border:1px solid var(--line);border-radius:999px;padding:5px 11px;cursor:pointer}body.theme-infernal #ib-helper-sheet .hp-chip{background:rgba(255,255,255,.06)}#ib-helper-sheet .hp-wait{display:inline-flex;gap:4px;align-items:center;height:14px}#ib-helper-sheet .hp-wait i{width:5px;height:5px;border-radius:50%;background:var(--tx3);opacity:.5;animation:hp-dot 1.1s ease-in-out infinite}#ib-helper-sheet .hp-wait i:nth-child(2){animation-delay:.18s}#ib-helper-sheet .hp-wait i:nth-child(3){animation-delay:.36s}@keyframes hp-dot{0%,100%{opacity:.25;transform:translateY(0)}50%{opacity:.9;transform:translateY(-2px)}}body.ib-reduce #ib-helper-sheet .hp-wait i{animation:none;opacity:.6}#ib-helper-sheet .hp-clr{flex:none;font-size:.7rem;color:var(--tx3);background:none;border:0;padding:4px 6px;cursor:pointer;font-family:inherit}'
+'#hp-gq{position:fixed;top:calc(8px + (50px*var(--szTop,1) - 28px)/2 + var(--sat,0px));right:calc(56px + var(--sar,0px));z-index:38;width:28px;height:28px;border-radius:50%;border:1px solid rgba(114,168,216,0.55);background:rgba(114,168,216,0.2);color:var(--acc);display:flex;align-items:center;justify-content:center;cursor:pointer;padding:0;box-shadow:0 0 10px rgba(114,168,216,0.18);-webkit-tap-highlight-color:transparent;transition:box-shadow .3s,border-color .3s}#hp-gq[hidden]{display:none}#hp-gq svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}#hp-gq:active{box-shadow:0 0 14px rgba(172,202,238,0.35);border-color:rgba(172,202,238,0.7)}body.theme-infernal #hp-gq{background:rgba(120,160,220,0.26);border-color:rgba(160,195,240,0.5);color:#dbe9ff}body.on-sub #hp-gq{display:none}'
+'.hp-gbtn{display:inline-flex;align-items:center;gap:8px;height:34px;padding:0 16px;margin-top:10px;border-radius:999px;border:1px solid rgba(114,168,216,0.55);background:rgba(114,168,216,0.2);color:var(--acc);font:inherit;font-size:.84rem;cursor:pointer}body.theme-infernal .hp-gbtn{background:rgba(120,160,220,0.26);border-color:rgba(160,195,240,0.5);color:#dbe9ff}.hp-gbtn svg{width:15px;height:15px;stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}'
+'#ib-helper-sheet .hp-api{flex:1;min-width:0;text-align:left;font-size:.72rem;color:var(--tx3);background:none;border:0;padding:0;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:inherit}#ib-helper-sheet .hp-api[disabled]{cursor:default}'
+'#hp-apimenu{position:absolute;left:14px;top:48px;z-index:6;min-width:220px;max-width:calc(100% - 28px);padding:8px;border-radius:14px;border:1px solid var(--line);background:#f2f7fd;box-shadow:0 14px 40px rgba(20,35,70,.18)}body.theme-infernal #hp-apimenu{background:#1b2740;border-color:rgba(165,188,230,.24);box-shadow:0 14px 40px rgba(0,0,0,.4)}#hp-apimenu .t{font-size:.7rem;color:var(--tx3);padding:4px 8px 8px}#hp-apimenu button{display:block;width:100%;text-align:left;font:inherit;font-size:.86rem;color:var(--tx);background:none;border:0;border-radius:9px;padding:9px 10px;cursor:pointer}#hp-apimenu button.on{background:rgba(114,168,216,.18);color:var(--acc)}#hp-apimenu button:active{background:rgba(114,168,216,.26)}'
/* 手机端：常驻快捷指令行（横向滑动、滚动条自绘＝隐藏、右缘渐隐提示可滑）；回复 Markdown（.mdr 照主聊天） */
+'#ib-helper-sheet .hp-q{display:flex;flex:none;gap:6px;overflow-x:auto;overflow-y:hidden;margin:0 -14px;padding:2px 40px 10px 18px;scrollbar-width:none;-webkit-overflow-scrolling:touch;-webkit-mask-image:linear-gradient(90deg,#000 calc(100% - 28px),transparent);mask-image:linear-gradient(90deg,#000 calc(100% - 28px),transparent)}#ib-helper-sheet .hp-q::-webkit-scrollbar{display:none}#ib-helper-sheet .hp-q .hp-chip{flex:none;white-space:nowrap;line-height:1.3;-webkit-tap-highlight-color:transparent}#ib-helper-sheet .hp-q .hp-chip:active{background:rgba(114,168,216,.22)}'
+'#ib-helper-sheet .hp-m.mdr{white-space:normal}#ib-helper-sheet .hp-m.mdr pre.md-cb{margin:6px 0}#ib-helper-sheet .hp-m.mdr ul,#ib-helper-sheet .hp-m.mdr ol{margin:4px 0}';
function inject(){if(document.getElementById('ib-helper-sheet'))return;
  var st=document.createElement('style');st.id='ib-helper-css';st.textContent=CSS;document.head.appendChild(st);
  var sc=document.createElement('div');sc.id='ib-helper-scrim';sc.hidden=true;document.body.appendChild(sc);sc.addEventListener('click',close);
  var sh=document.createElement('div');sh.id='ib-helper-sheet';sh.innerHTML='<div class="hp-h"><b>小助手水水</b><button class="hp-api" id="hp-api" type="button" title="切换水水用的 API"></button><button class="hp-clr" id="hp-clr" type="button">清空</button><button class="hp-x" type="button" aria-label="关闭">×</button></div><div class="hp-q" id="hp-q">'+QUICK.map(function(q){return '<span class="hp-chip" data-q="'+esc(q[1])+'">'+esc(q[0])+'</span>'}).join('')+'</div><div class="hp-list" id="hp-list"></div><div class="hp-in"><textarea id="hp-ta" rows="1" placeholder="问它怎么用，或让它直接改"></textarea><button class="hp-send" id="hp-send" type="button" aria-label="发送"><svg viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6"/></svg></button></div>';document.body.appendChild(sh);
  sh.querySelector('.hp-x').addEventListener('click',close);
  sh.querySelector('#hp-clr').addEventListener('click',function(){S.hist=[];S.undo=[];persist();paintAll()});
  sh.addEventListener('click',function(e){var c=e.target.closest&&e.target.closest('.hp-chip');if(c){var ta=document.getElementById('hp-ta');if(ta){ta.value=c.getAttribute('data-q')||c.textContent;submit()}}});
  var ta=sh.querySelector('#hp-ta');ta.addEventListener('input',function(){ta.style.height='auto';ta.style.height=Math.min(96,ta.scrollHeight)+'px'});ta.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submit()}});
  sh.querySelector('#hp-send').addEventListener('click',submit);
  sh.querySelector('#hp-api').addEventListener('click',function(e){e.stopPropagation();apiMenu()});
  try{if(!document.getElementById('hp-gq')){var gq=document.createElement('button');gq.id='hp-gq';gq.type='button';gq.title='问水水';gq.setAttribute('aria-label','问水水');gq.hidden=true;gq.innerHTML='<svg viewBox="0 0 20 20"><path d="M7.2 7.4a2.9 2.9 0 1 1 4.4 2.5c-1 .6-1.6 1.2-1.6 2.3"/><circle cx="10" cy="15.3" r=".9" fill="currentColor" stroke="none"/></svg>';gq.addEventListener('click',function(e){e.stopPropagation();open()});document.body.appendChild(gq)}}catch(e){}/* GUIDE 页顶「?」圆钮（主题水滴左侧） */
  try{var go=document.getElementById('hp-gopen');if(go&&!go._hp){go._hp=1;go.addEventListener('click',function(e){e.stopPropagation();open()})}}catch(e){}/* GUIDE「小助手」块里的「打开水水」 */
  try{S.hist=JSON.parse(localStorage.getItem('ib_helper_hist')||'[]');if(!Array.isArray(S.hist))S.hist=[]}catch(e){S.hist=[]}
  paintAll()}
function callOpen(){try{var c=document.getElementById('ibcall');return !!(c&&!c.hidden)}catch(e){return false}}
function vis(){try{var gq=document.getElementById('hp-gq');if(!gq)return;var ov=!!document.querySelector('.sheet.open,#ov2.on,#fav-ov:not([hidden])');gq.hidden=!(typeof currentPage!=='undefined'&&currentPage==='guide'&&!S.open&&!ov)}catch(e){}}
function relabel(){var ap=document.getElementById('hp-api');if(!ap)return;var c=cfgOf();ap.textContent=c?('执笔 API · '+cfgLabel(c)+' ▾'):'还没有可用的 API';ap.disabled=!cfgList().length}
function apiMenu(){var old=document.getElementById('hp-apimenu');if(old){old.remove();return}var l=cfgList();if(!l.length){if(typeof toast==='function')toast('先到 API 页添加一个 API');return}var sh=document.getElementById('ib-helper-sheet'),ap=document.getElementById('hp-api');if(!sh)return;var cur=(cfgOf()||{}).id;
  var m=document.createElement('div');m.id='hp-apimenu';m.innerHTML='<div class="t">执笔 API — 水水用哪个 API 回答</div>'+l.map(function(c){return '<button type="button" data-id="'+esc(c.id)+'"'+(c.id===cur?' class="on"':'')+'>'+esc(cfgLabel(c))+'</button>'}).join('');sh.appendChild(m);
  m.addEventListener('click',async function(e){var b=e.target.closest('button');if(!b)return;e.stopPropagation();try{if(typeof loadMP==='function')await loadMP()}catch(x){}hp().api=b.getAttribute('data-id');await save();relabel();m.remove();if(typeof toast==='function')toast('水水改用：'+(cfgLabel(cfgOf())||'—'))});
  setTimeout(function(){function off(e){if(!m.isConnected){document.removeEventListener('pointerdown',off,true);return}var p=e.composedPath?e.composedPath():[];if(p.indexOf(m)>=0||(ap&&p.indexOf(ap)>=0))return;m.remove();document.removeEventListener('pointerdown',off,true)}document.addEventListener('pointerdown',off,true)},0)}
function open(){inject();var sh=document.getElementById('ib-helper-sheet'),sc=document.getElementById('ib-helper-scrim');S.open=true;vis();sc.hidden=false;(async function(){try{if(typeof loadMP==='function')await loadMP()}catch(e){}relabel();requestAnimationFrame(function(){sh.classList.add('on');var l=document.getElementById('hp-list');if(l)l.scrollTop=l.scrollHeight})})()}
function close(){var sh=document.getElementById('ib-helper-sheet'),sc=document.getElementById('ib-helper-scrim');var am=document.getElementById('hp-apimenu');if(am)am.remove();if(sh)sh.classList.remove('on');if(sc)sc.hidden=true;S.open=false;vis()}
function paintAll(){var l=document.getElementById('hp-list');if(!l)return;l.innerHTML='';if(!S.hist.length){l.innerHTML='<div class="hp-tip">我是水水，作者的分身 (๑˃̵ᴗ˂̵)و<br>问我某个功能在哪、怎么用，或者直接让我改设置——改完会列出改了什么，都能撤销。上面一排是常用问题，点一下就发。</div><div class="hp-tip hp-tip2">你可以通过这个电子邮箱联系到作者：1282901880@qq.com；PWA与桌面端项目在Github免费开源，采用PolyForm Noncommercial License 1.0.0非商业版权协议。PWA移动端地址：github.com/Sui-IB/InternalBeyond-Mobile、桌面端地址：github.com/Sui-IB/InternalBeyond，付费买到这些版本的都是倒卖哦。 (｡･ω･｡)ﾉ♡</div>';return}S.hist.forEach(function(m){addBubble(m.role,m.text,m.acts,false)})}
function addBubble(role,text,acts,scroll){var l=document.getElementById('hp-list');if(!l)return null;var d=document.createElement('div');d.className='hp-m '+(role==='user'?'u':'a');if(role!=='user'&&typeof mdRenderHtml==='function'){d.classList.add('mdr');try{d.innerHTML=mdRenderHtml(String(text||''),false)}catch(e){d.textContent=text||''}}else d.textContent=text||'';/* 手机端：回复与主聊天同一套 Markdown 渲染 */if(acts&&acts.length)acts.forEach(function(a){var r=document.createElement('div');r.className='hp-act'+(a.ok?'':' err');r.innerHTML='<i></i><b>'+esc(a.line)+'</b>'+(a.undoIdx!==undefined?'<u>撤销</u>':'')+(a.jump?'<u class="jump">跳转 →</u>':'');var u=r.querySelector('u:not(.jump)');if(u)u.addEventListener('click',function(){undo(a,u)});var j=r.querySelector('u.jump');if(j)j.addEventListener('click',function(){try{navTo(a.jump)}catch(e){}close()});d.appendChild(r)});l.appendChild(d);if(scroll!==false)l.scrollTop=l.scrollHeight;return d}
async function undo(a,u){if(u.classList.contains('done'))return;var it=S.undo[a.undoIdx];if(!it)return;try{await write(it.path,it.old);u.textContent='已撤销';u.classList.add('done');if(typeof toast==='function')toast('已撤销：'+labelOf(it.path))}catch(e){if(typeof toast==='function')toast('撤销失败')}}
function persist(){try{localStorage.setItem('ib_helper_hist',JSON.stringify(S.hist.slice(-30).map(function(m){return{role:m.role,text:m.text,acts:(m.acts||[]).map(function(a){return{ok:a.ok,line:a.line}})}})))}catch(e){}}
function submit(){var ta=document.getElementById('hp-ta');var t=(ta&&ta.value||'').trim();if(!t||S.busy)return;ta.value='';ta.style.height='auto';send(t)}
function parse(raw){var acts=[],guides=[];var text=String(raw||'');
  text=text.replace(/<guide\s+section="([^"]*)"\s*\/?>(?:\s*<\/guide>)?/gi,function(_,n){guides.push(n);return ''});
  text=text.replace(/<act\s+([^>]*?)\/?>(?:\s*<\/act>)?/gi,function(_,attrs){var a={};attrs.replace(/([a-z]+)\s*=\s*"([^"]*)"/gi,function(__,k,v){a[k.toLowerCase()]=v});if(a.op)acts.push(a);return ''});
  return{text:text.replace(/\n{3,}/g,'\n\n').trim(),acts:acts.slice(0,5),guides:guides}}
async function send(q){var cfg=cfgOf();S.hist.push({role:'user',text:q});addBubble('user',q);
  if(/^(你是谁|你是什么|你叫什么|你是啥|水水是谁|你的名字|whoareyou)$/i.test(q.replace(/[\s？?！!。.~～、,，]/g,''))){var wm={role:'assistant',text:WHO};S.hist.push(wm);addBubble('assistant',wm.text);persist();return}/* 唯一答案，本地直答、不走 API */
  if(/^图片(探针|诊断)[？?]?$/.test(q)){var il=(window._ibImgDiagLog||[]).slice(-6);var im={role:'assistant',text:il.length?('最近 '+il.length+' 次带图请求的去向：\n\n'+il.map(function(x){var t=new Date(x.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});return '- '+(x.ok?'✓ ':'✗ ')+t+' · '+x.who+(x.model?'（'+x.model+'）':'')+'：'+(x.sent?('带 '+x.n+' 张图发出，'+(x.ok?'服务端接受（HTTP '+x.status+'）':'被拒（HTTP '+x.status+'）'+(x.err?'：'+x.err:''))):('去图重发（原带 '+x.n+' 张），'+(x.ok?'成功':'仍失败（HTTP '+x.status+'）')))}).join('\n')+'\n\n被拒＝这个 API / 中转 / 模型不收 image_url 或图太大，IB 已自动去图重发一次（所以 TA 只看到 [图N] 标记）；接受了但 TA 说看不到＝模型本身不识图或中转把图丢了，换识图型号或换中转。'):'还没有记录。让 TA 查看一条带图的动态、或直接发一张图给 TA 之后再来看。'};S.hist.push(im);addBubble('assistant',im.text);persist();return}
  if(/^缓存(探针|诊断|命中)?[？?]?$/.test(q)){var lg=(window._ibCacheDiagLog||[]).slice(-6);var pm={role:'assistant',text:lg.length?('最近 '+lg.length+' 轮的前缀比对（对同一位 TA，每轮请求发出前与上一轮逐字比对）：\n\n'+lg.map(function(x){return '- '+(x.ok?'✓ ':'✗ ')+new Date(x.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+' · '+x.who+'：'+(x.ok?'system 与历史前缀稳定（'+x.d+' / '+x.total+' 字符）':'第 '+x.d+' 字符起不一样（上一轮最新消息起点 '+x.last+'）')}).join('\n')+'\n\n✓ 这轮能命中上一轮的缓存；✗ system 或历史前缀变了，缓存重建一次。版本更新、改人设、拨任何协议开关、always 条目改动之后的第一轮出一个 ✗ 属正常，连着 ✗ 才是问题。'):'还没有记录。给任一位 TA 连发两条消息后再来看。'};S.hist.push(pm);addBubble('assistant',pm.text);persist();return}
  if(/^设置(清单|列表|表)[？?]?$/.test(q)){(async function(){try{if(typeof loadCALL==='function')await loadCALL()}catch(e){}try{if(typeof loadOUT==='function')await loadOUT()}catch(e){}
    var rs=registry(),gu=[],gg=[],gl=[],gp={},shown=0;rs.forEach(function(r){var lb=r.label||LABEL[r.path]||'';
      if(r.path.indexOf('api.')===0||r.path.indexOf('call.')===0||r.path.indexOf('perAi.')===0){var id=r.path.split('.')[1];(gp[id]=gp[id]||{n:0,nm:''});gp[id].n++;if(!gp[id].nm&&lb){var m9=/「([^」]+)」/.exec(lb);if(m9)gp[id].nm=m9[1]}return}
      if(!lb)return;
      var line='· '+friendly(lb,r.val);shown++;
      if(r.path.indexOf('ui.')===0)gu.push(line);else if(r.path.indexOf('local.')===0)gl.push(line);else gg.push(line)});
    var per=Object.keys(gp).map(function(id){var x=gp[id];return '· '+(x.nm||'一位好友')+'：'+x.n+' 项（API 配置 / 通话 / 手机端参数；想逐项看就说「看看 '+(x.nm||'TA')+' 的设置」）'}).join('\n');
    var sm={role:'assistant',text:'现在能直接改的一共 '+shown+' 项'+(per?'，另有每位好友各自的一组':'')+'：\n\n**全局与权限**\n'+gg.join('\n')+'\n\n**视觉**\n'+gu.join('\n')+'\n\n**本机**\n'+gl.join('\n')+(per?'\n\n**每位好友**\n'+per:'')+'\n\n想改哪项，直接说效果就行。 (⁎˃ᴗ˂⁎)'};
    S.hist.push(sm);addBubble('assistant',sm.text);persist()})();return}
  if(!cfg){var m0={role:'assistant',text:'还没有可用的 API。先在 API 页添加一个，回来点上面的「执笔 API」选一个。'};S.hist.push(m0);addBubble('assistant',m0.text);persist();return}
  S.busy=true;var sb=document.getElementById('hp-send');if(sb)sb.disabled=true;var wait=addBubble('assistant','');if(wait)wait.innerHTML='<span class="hp-wait"><i></i><i></i><i></i></span>';
  try{var extra=[],hops=0,raw='',res=null;
    try{if(typeof loadCALL==='function')await loadCALL()}catch(e){}try{if(typeof loadOUT==='function')await loadOUT()}catch(e){}/* 设置表里通话每联系人项读 _callS、输出与工具项读 _out，先保证都已从库里读过 */
    var msgs=[];S.hist.slice(-12).forEach(function(m){var r=m.role==='user'?'user':'assistant',c=String(m.text||'');if(!msgs.length&&r!=='user')return;if(msgs.length&&msgs[msgs.length-1].role===r){msgs[msgs.length-1].content+='\n'+c;return}msgs.push({role:r,content:c})});/* 手机端：user 起首、角色交替（Anthropic 报文要求） */
    var test=Object.assign({},cfg,{streaming:false,thinkingEnabled:false,promptCache:false,webSearch:false});/* 手机端：水水不带联网搜索工具 */
    for(;;){var r=await Promise.race([callAI(test,msgs,buildSys(q,extra),function(){},null,null),new Promise(function(_,rej){setTimeout(function(){rej(new Error('等了 120 秒还没回，稍后再试'))},120000)})]);raw=String((r&&typeof r==='object')?(r.t||''):(r||''));if(!raw.trim()&&r&&r.k)raw=String(r.k);
      res=parse(raw);if(res.guides.length&&hops<2){var add=res.guides.map(section).filter(Boolean);if(!add.length)break;extra=extra.concat(add);hops++;continue}break}
    var acts=[];for(var i=0;i<res.acts.length;i++){var a=res.acts[i],o;try{o=a.op==='set'?await doSet(a.path,a.value):a.op==='open'?doOpen(a.page):a.op==='run'?await doRun(a.name,a.arg):{ok:false,msg:'不认识的动作 '+a.op}}catch(e){o={ok:false,msg:String(e&&e.message||e)}}
      acts.push(o.ok?{ok:true,line:o.noop?(o.label+'：本来就是 '+o.to):(o.label+(o.from!==undefined?'：'+o.from+' → '+o.to:'')),undoIdx:o.undoIdx,jump:o.jump}:{ok:false,line:o.msg||'失败'})}
    var txt=res.text||(acts.length?'已处理。':'（没有返回内容）');if(wait)wait.remove();var am={role:'assistant',text:txt,acts:acts};S.hist.push(am);addBubble('assistant',txt,acts);
  }catch(e){if(wait)wait.remove();var em={role:'assistant',text:'请求失败：'+String(e&&e.message||e).slice(0,160)};S.hist.push(em);addBubble('assistant',em.text)}
  S.busy=false;if(sb)sb.disabled=false;persist()}
function boot(){(async function(){try{if(typeof loadMP==='function')await loadMP()}catch(e){}inject();vis();
  try{if(typeof navTo==='function'){var _nt9=navTo;navTo=function(){var r=_nt9.apply(this,arguments);try{vis()}catch(e){}return r}}}catch(e){}
  setInterval(vis,1500)})()}
window.IBHelper={open:open,close:close,registry:registry,vis:vis};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
})();
