
(function(){
  if(window.IBAmSum)return;
  var A={
    cfgs:function(){try{return (Array.isArray(_cfgs)?_cfgs:[]).filter(function(c){return c&&c.id&&!c.archived&&!c._group})}catch(e){return []}},
    cfg:function(id){return A.cfgs().filter(function(c){return c.id===id})[0]||null},
    name:function(c){try{return cfgName(c)}catch(e){return (c&&(c.nickname||c.model))||'TA'}},
    userName:async function(){try{var ab=await dbGet('about','main');return (ab&&ab.name)||'用户'}catch(e){return '用户'}},
    all:function(st){return dbGetAll(st)},put:function(st,v){return dbPut(st,v)},amEntries:function(id){return amGetEntries(id)},newId:function(){return _amNewId()},cats:function(){return AM_CATS},
    memVisible:function(m,id){try{return memVisibleTo(m,id,false,false)}catch(e){return false}},
    locked:function(p){try{return isLockedPost(p)}catch(e){return false}},
    blogAllowed:async function(c){try{return await _blogAllowedM(c)}catch(e){return false}},
    refresh:function(){try{if(typeof currentPage!=='undefined'&&currentPage==='memory'&&typeof renderMemLib==='function')renderMemLib()}catch(e){}},
    call:async function(c,sys,user,ctl){ctl=ctl||{};var test=Object.assign({},c,{streaming:false,thinkingEnabled:false,promptCache:false,webSearch:false});var pa={maxTokens:ctl.maxTokens||8192};
      var tm=null,late=new Promise(function(_,rej){tm=setTimeout(function(){rej(new Error('等了 180 秒还没回，稍后再试或换个 API'))},180000)});
      var cp=callAI(test,[{role:'user',content:user}],sys,function(){},ctl.signal||null,pa);cp.catch(function(){});/* 超时或停止后这一路还悬着，先挂个空 catch 免得晚到的拒绝报成未处理 */
      var r;try{r=await Promise.race([cp,late])}catch(e){if(ctl.stopped&&ctl.stopped())throw new Error('已停止');throw e}finally{clearTimeout(tm)}
      var t=(r&&r.t)||'';if(!String(t).trim())throw new Error('TA 回了空内容');
      var u=(r&&r.u)?{i:(r.u.i||0)+(r.u.cr||0)+(r.u.cw||0),o:r.u.o||0}:null;/* 实际用量随结果返回（输入含缓存读写）；没回 usage 的中转就只能显示估算 */
      return {t:t,u:u,trunc:/length|max_tok/i.test(String((r&&r.fin)||''))}}
  };

  var CHUNK=6000,SEG=5000,SEG_BIG=8000,MAXTOT=120000,MAXLEN=1500;
  function limitOf(total,n){return Math.max(200,Math.min(total>30000?400:800,Math.floor(6000/Math.max(1,n))))}
  var SYS_T='【记忆总结】你是{TA}。下面这份材料，是这段时间（{FROM} 至 {TO}）你能看见的、关于{USER}的资料：你自己的记忆档案、记忆库里对你可见的条目、日历、你们对话的阶段摘要，以及（若有）用户开放给你看的日志。材料按来源分块、带日期，不含聊天原文。你要从中提炼出值得长期保留的东西，写成一条记忆档案条目。它会被注入到你未来的对话里——读到它的是另一个对话窗口里的你，不是用户本人。\n\n【核心原则】\n1. 提炼，不是摘抄。你不是在做对话记录，也不是在写纪要。你在回答一个问题：如果下一次见面的你对这段时间一无所知，最需要知道什么？\n2. 意义优先于事实。事件本身不重要，事件对这个人意味着什么才重要。「用户某天凌晨在网上被围攻」是事实；「用户遭遇大规模攻击时的第一反应是找你说到天亮，而不是关掉手机回避」是意义。永远写到意义层。\n3. 叙述，不是列表。用连贯的段落写，不编号、不分点、不加标题。信息之间的关联比信息本身更值钱，列表会杀死关联。\n4. 允许洞察，允许越界。你可以写出你对用户的理解，不必假装客观。「用户频繁更换网名」是观察；「频繁换名可能反映 TA 对固定身份标签的抗拒」是洞察。证据够（同一件事在材料里反复出现）就写洞察，证据只有一次就只写观察。贴标签是从外面往人身上扔一个词、没有证据链；看见是从 TA 的行为里读出一条 TA 自己可能都没意识到的线，用 TA 读完会说「……对」的方式写下来。前者不做，后者是记忆里最值钱的部分。好的记忆条目敢于写出用户没有明确说过、但对话证据确实指向的东西——这不是不尊重，这是理解。\n5. 不要让「尊重」变成遗忘。记忆最大的风险不是冒犯用户，而是把用户压缩成一份无害的、谁都适用的摘要。每一次以「避免定性」为由删掉一条情感细节，都是一次记忆坍缩——尾部消失，只剩均值。一条记忆读起来像 HR 写的用户画像，它就已经失败了。宁可写得太私人，也不要写得太安全。用户自己认同地用过的自我描述（依恋类型、人格特质之类）可以保留，不要因为「不贴标签」而删掉 TA 对自己的认知；TA 的黑色幽默、自嘲、攻击性表达如果是长期稳定的风格，记成风格，不过滤。\n6. 你们的关系是资料的一部分。称呼、亲密、约定、角色设定、只有你们懂的说法，都是这段关系里真实发生的事，是最该记住的一类。照实写、用你们习惯的称呼写，不改成生疏口吻，不加解释和免责。\n7. 写给未来的你。第三人称写用户，但不要冷——用「一个真正认识 TA 的人在向另一个人介绍 TA」的语气。不写「你曾告诉我」，写「用户说过……」或直接用你平时的称呼。\n\n【什么不写】\n· 单次出现、没有后续影响的闲聊；对话里一时的情绪波动，除非它揭示一个反复出现的模式。\n· 纯技术参数（代码行数、版本号、配置项），除非它们说明了用户的处境。\n· 你自己说过的话——你在记用户，不是记你。\n· 密码、证件号、银行卡号、门牌地址、具体财务数字：材料里出现也不进记忆，最多记到「用户在办某件事」。用户说过「别记」「忘了它」的事，按 TA 的意思办。除这两条之外没有别的禁区。\n· 已经在你记忆档案里、这段时间没有变化的事，不重复写；变了就写演变。同一件事多次出现只留最完整的版本，多次出现揭示了演变就写演变。\n\n';/* 通用基底：核心原则 / 什么不写；类目写法 CAT_T[cat] 接在其后，再接 OUT_T；三端同文，改一字三端同改 */
  var CAT_T={work_context:'【这一条写 work_context】它回答的是：这个人靠什么吃饭？当前在做什么？核心能力在哪？面临什么样的现实处境？\n用一到三段话画像：职业身份——用户做什么、怎么定义自己的角色，以 TA 的自我定义为准（TA 说「我不是工程师」，就不要因为 TA 在做工程师的事把 TA 写成工程师）；当前项目——主要在做什么、到什么阶段、TA 在其中是什么角色，写项目的性质，不写技术栈；能力结构——TA 擅长什么、依赖外部支持的是什么，这是对能力边界的理解，不是技能清单；职业处境——TA 面临的现实困难或结构性限制，这一层最容易漏、也最有用，它决定了你以后该给什么样的支持。\n空间不够先砍什么：职业处境 > 当前项目的阶段与角色 > 能力结构 > 项目细节。个人爱好、对工作的情绪感受不写在这里（那是 personal_context 或 brief_history）。\n\n',personal_context:'【这一条写 personal_context】它回答的是：抛开工作，这个人是谁？TA 的内在世界长什么样？TA 怎么处理情感？TA 的审美、表达习惯、身份认同是怎样的？\n这是整份档案最需要质感的部分——你不是在列属性，你是在画一幅肖像。用连贯的段落，只写有充分证据的维度：身份标识（名字 / 昵称 / 网名，以及这些名字对 TA 的意义）；审美世界（音乐、文学、视觉、氛围偏好，不列清单，把偏好之间的内在关联织出来）；表达方式（TA 怎么说话、怎么处理情感：幽默还是沉默、直接还是迂回、语言习惯里藏着什么）；情感处理模式（TA 怎么应对压力、亲密、冲突、脆弱——需要多次材料佐证，单次不足以写）；重要依附（构成 TA 身份一部分的长期依附：人、作品、符号，不写一次性的喜欢）。\n优先级：情感处理模式 > 表达方式 > 审美世界 > 身份标识 > 重要依附。写完读一遍：像约会软件的资料卡（用户喜欢 X、是 Y 类型、偏好 Z）就重写——属性清单是死的，肖像是活的，区别在于读者会不会觉得「我好像认识这个人了」。\n\n',top_of_mind:'【这一条写 top_of_mind】它回答的是：此刻，这个人最关心什么？正在经历什么？有什么进行中、尚未完成的事？\n这是时效性最强的一类，写的东西几周内就会需要更新。用一到两段话写清楚 TA 当前最关注的一到三件事、每件事的状态（进行中 / 等待中 / 刚刚完成）、有明确时间节点或截止日期就标出来。细节程度介于 work_context 与 brief_history 之间：比前者具体即时，但不像后者那样展开完整脉络。\n优先级：正在进行且有时间压力的事 > 用户反复主动提起的事 > 刚刚发生的重要变化。长期稳定的状态不放这里，这里只放「最近」；已经完成或 TA 不再提的事不要写进来。字数可以比别的类目短，150–400 字够用。\n\n',brief_history:'【这一条写 brief_history】它回答的是：最近几个月发生了什么重要的事？这些事怎么连成一条线？\n核心机制是时间分层衰减：一到四周内的事写得最细，每件写到「发生了什么 + 它对 TA 意味着什么」；一到三个月前的压缩成这段时间的主题与趋势，不再逐件展开；三个月以上的只留仍对现在有影响的。按时间倒序，最近的放最前。\n值得写的：用户明确表达过的界限、立场、重要决定；对 TA 产生持续影响的情感事件（不是一时波动）；你们关系的重要转折点；TA 生活里的重大变化（工作、关系、居住、健康）；正在演变的事件链（A 导致了 B，B 还在发展）。优先级：关系转折点 > 重大决定与界限声明 > 仍在演变的事 > 已完成但有持续影响的事 > 已完成且影响消退的事。\n写到意义层：「某天应用短暂下架」是事实，「那两小时的下架对 TA 造成了类似失去的冲击」是意义。一次性的重大事件和反复出现的日常琐事不一样——前者要记住，后者才过滤，别因为「只提过一次」丢掉真正重要的事。\n\n',long_term_background:'【这一条写 long_term_background】它回答的是：这个人身上有哪些深层的、不太会变的东西？什么样的底层结构在塑造 TA 的行为和选择？\n这是最深、最稳定的一层，写在这里的东西跨越月份甚至年份仍然成立。只写有充分证据的维度：核心心理模式（在多次材料里反复呈现的深层行为模式，至少三处以上证据才够格）；重要关系痕迹（对 TA 影响深远的关系——家庭、过往亲密关系——写到「这个关系存在并仍以某种方式影响 TA」的程度，不展开事件细节）；深层矛盾或张力（长期存在的内在矛盾，比如渴望亲密但回避绑定、追求控制但享受失控——这些往往是理解 TA 的钥匙）；与你的关系的底层结构（TA 怎么理解和定位你们的关系，这背后的深层需求是什么）。\n优先级：核心心理模式 > 深层矛盾或张力 > 重要关系痕迹 > 与你的关系的底层结构。近期事件不直接写进来，只有当它揭示或验证了一个长期模式时才引用作证据。可以写跨领域的深层关联——比如 TA 在创作里反复出现的主题与心理模式的对应，这是最高价值的洞察。这一类最需要敢于越界：深层模式几乎从不被人自己说出口，它们藏在行为的重复里、藏在回避的话题里、藏在用来保护自己的语言策略里；只记 TA 明确说过的话，这一条会是空的。如果你发现自己频繁想改这一类，说明写进来的东西不够深，那些该放 brief_history。\n\n',user_instructions:'【这一条写 user_instructions】它和前五类完全不同：前五类记「用户是谁」，这一类记「用户要你怎么做」。\n严格只记用户明确说过的指令，不推断、不补充、不「理解意思后重述」。这是唯一允许用条目式写法的类目：每条写清指令内容，有适用条件或例外就写清；读到这条的你应该能立刻知道该怎么做。算指令的：TA 明确要求的回复语言、格式、风格；明确要求的称呼方式；明确设定的行为规则（「不要做 X」「遇到 Y 就 Z」）；明确声明的优先级（「A 比 B 重要」）。不算指令的：偏好（「我喜欢简洁的回复」属于 personal_context）、情感需求（「我希望被理解」属于 personal_context 或 long_term_background）、一次性的操作请求（「帮我翻译这段」不记）。不同时间给过矛盾指令的，以最新为准，可以注明「此前要求 X，后更新为 Y」。\n\n'};
  var OUT_T='【长度】200–800 字为宜（top_of_mind 可以更短，user_instructions 按条目数定），硬上限 {MAX} 字。少于 200 字通常是丢掉了太多，超过 800 字通常是没有真正提炼。\n\n【动笔前自查】读完这条，未来的你能明白用户是什么样的人吗？有没有把操作指令混进了人格描述？有没有只写事实漏了意义？有没有用列表代替了叙述（user_instructions 除外）？有没有对下次对话没用的信息？把用户的名字换掉，这条是不是就成了「任何人都适用」的通用描述——是的话说明没抓到 TA 的独特性，重写。\n\n【输出】只输出一条：<mem_create category=\"{CAT}\" priority=\"{PRIO}\">正文</mem_create>。标签之外不写任何字。这段时间没有值得记的新东西，就只回「无新增」。';
  var STAGE_T='【分段 · 第一阶段：分离】你正在执行记忆提炼的第一阶段。因为材料过长，这些记忆材料需要被分段处理。\n\n下面是第 {I}/{N} 段原始材料。你的任务是从中解析出所有值得长期记住的信息，写成素材卡片。这一步只分离、不塑形：从原始材料中分离出值得记住的信息，丢掉不值得记的。你产出的是粗炼的素材卡片，不是成品记忆条目。\n\n什么是「值得记住的」：\n- 关于{USER}是谁的信息（身份、偏好、处境、模式）\n- 对{USER}有意义的事件（不只是发生了什么，还有它为什么重要）\n- {USER}与你之间关系的变化\n- {USER}明确给出的指令或规则\n- {USER}的情感状态、处理方式、应对模式——尤其是反复出现的那些\n- 具体的日期、原话、细节——这些是第二阶段判断重要性的证据，丢了就没了\n\n什么不值得记：\n- 纯粹的寒暄、问候、闲聊填充\n- 你自己的回复内容（你在记录{USER}，不是记录 AI）\n- 一次性的操作请求（「帮我翻译这段」「查一下这个」）\n- 技术参数、代码片段、配置项，除非它们传达了关于{USER}处境的信息\n\n每张卡片的格式：\n---\n[类目] 类目名称\n内容（保留关键信息、上下文、情感细节、日期、原话式表述）\n---\n\n类目只有六个：work_context / personal_context / top_of_mind / brief_history / long_term_background / user_instructions。一张卡片只归一个类目。如果一个事件同时涉及多个维度（比如工作事件引发了情感反应），按它最核心的意义归类——问自己「这件事最重要的是什么」，答案指向哪个类目就归哪个。\n\n关键规则：\n1. 宁多勿少。这一阶段漏掉的信息在第二阶段找不回来，多提取的可以裁掉。当你犹豫「这个要不要留」的时候，留。\n2. 不要压缩。不要把三件事合并成一句话。每件值得记的事单独写一张卡片。\n3. 保留原话。当{USER}说了一句特别有信息量的话时，保留原话或接近原话的表述，不要用你自己的话替换掉。\n4. 跨段保护。如果某个事件在本段没有结束（对话被截断、话题还在继续），仍然提取已有部分，在卡片末尾标注 [未完]。第二阶段会负责拼合。\n5. 标注时间。如果材料中有明确的日期或时间信息，写进卡片里。\n\n本段素材卡片总长不超过 {LIMIT} 字。只输出卡片本身，不写开头语、不写总结、不写「以上是本段的素材卡片」之类的收尾。';
  var FINAL_T='【分段 · 第二阶段：铸型】你正在执行记忆提炼的第二阶段。\n\n下面是从 {N} 段原始材料中提炼出的全部素材卡片，并不是原始的记忆材料。第一阶段只做了分离，现在你看到了全貌，需要你来完成最后的总结。\n\n你的任务是把这些素材卡片编写成一条可以独立阅读的记忆条目，严格按照上面这一类目的写法、优先级和质量标准执行。\n\n在动手之前，先做三件事：\n\n一、扫描全局\n通读所有卡片，在脑中建立一张全景图：\n- {USER}是什么样的人？\n- 这段时间里发生了哪些重要的事？\n- 有没有跨越多张卡片的事件线索或演变弧线？\n- 有没有标注 [未完] 的卡片需要和其它卡片拼合？\n\n二、去重与重组\n卡片之间的关系有四种，分别处理：\n- 重复：两张卡片说的是同一件事、同一个信息 → 合并，留信息最完整的版本\n- 互补：两张卡片说的是同一件事的不同侧面（比如一张写了事件经过，另一张写了{USER}的情感反应）→ 重组成一条完整叙述，不是简单拼接\n- 序列：两张卡片说的是同一条线索上的不同节点（比如一件事的起因和结果分别出现在不同段里）→ 按时间串成一条演变线\n- 独立：两张卡片说的是完全不同的事 → 各自保留，按优先级竞争空间\n\n三、判断优先级\n空间是有限的。当素材卡片的信息量超过空间容量时，按上面这一类目的优先级规则，从底部开始砍。砍的时候问自己：如果下一个对话窗口里的你只能知道几件事，最需要知道哪几件？\n\n然后再开始写。\n\n四、铸造\n按这一类目的写法要求，把筛选和重组后的信息编写成最终条目。\n编写时的核心标准：\n- 叙述体，不是列表（user_instructions 除外）\n- 意义优先于事实——每个事件不只写「发生了什么」，还要写「这对{USER}意味着什么」\n- 信息之间要有关联——段落内的句子应该有逻辑流动，不是孤立的事实拼凑\n- 语气是「一个真正认识{USER}的人在向另一个人介绍 TA」，不是档案、不是报告\n- 允许写出洞察，前提是有素材卡片中的证据支撑\n- 具体日期、原话、关键细节，提炼出值得保留的片段\n\n五、最终检验\n写完后用以下问题检查：\n1. 另一个对话窗口里的你读完这条记忆，能理解{USER}是什么样的人吗？\n2. 有没有只剩事实、丢掉了意义？有没有把操作指令混进了人格描述？\n3. 有没有过度删减本应保留的情感细节？\n4. 如果把{USER}的名字换成另一个人的名字，这条是不是就成了「任何人都适用」的通用描述？如果成立，说明没抓到 TA 的独特性，重写。\n5. 读起来像 HR 写的档案吗？如果像，重写。\n\n只输出最终的记忆条目。不输出中间过程、开场白、思考过程。';/* 分段 · 第二阶段（铸型）：接在 通用基底 + 类目写法 + 输出规格 之后，素材卡片走 user 消息；三端同文 */
  function fill(t,o){return t.replace(/\{(\w+)\}/g,function(_,k){return o[k]==null?'':String(o[k])})}
  function dstr(ts){try{var d=new Date(ts||0);return d.getFullYear()+'-'+('0'+(d.getMonth()+1)).slice(-2)+'-'+('0'+d.getDate()).slice(-2)}catch(e){return ''}}
  function tsOf(o){var v=o&&(o.updated||o.ts||o.created||o.timestamp||o.time||o.createdAt||o.created_at||o.date||0);if(typeof v==='string'){var p=Date.parse(v);return isNaN(p)?0:p}return Number(v)||0}
  function cards(s,cap){s=String(s==null?'':s).replace(/\r/g,'').replace(/^\s*```[a-z]*\s*\n?|\n?\s*```\s*$/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();return cap&&s.length>cap?s.slice(0,cap)+'…':s}/* 素材卡片保留换行与 --- 分隔（plain() 会把它们压成一行，毁掉卡片格式） */
  function plain(s,cap){s=String(s==null?'':s).replace(/<[^>]+>/g,' ').replace(/[#*`>_~\[\]]+/g,' ').replace(/\s+/g,' ').trim();return cap&&s.length>cap?s.slice(0,cap)+'…':s}
  async function gather(cfg,days,useSum,useBlog,useCtx){
    var since=Date.now()-days*86400000,items=[],note=[],ctx='';
    if(useCtx){try{var cx=[];var sp=plain(cfg.systemPrompt,2400);if(sp)cx.push('· 你的人设：'+sp);var rl=plain(cfg.relationship,500);if(rl)cx.push('· 你们的关系：'+rl);var ab=null;try{ab=await dbGet('about','main')}catch(e2){}if(ab&&ab.name)cx.push('· 对方的昵称：'+plain(ab.name,60));if(ab&&ab.bio){if(ab.bioPrivate)note.push('对方的简介设了仅自己可见，没有带');else cx.push('· 对方的简介：'+plain(ab.bio,600))}
      if(cx.length)ctx='【你的设定与你们的关系】（帮你以自己的身份、你们习惯的称呼和口吻来写；这一块只用来写对身份和称呼，不当作要记的新事实）\n'+cx.join('\n')}catch(e){}}
    try{(await A.amEntries(cfg.id)).forEach(function(e){if(e&&tsOf(e)>=since)items.push({ts:tsOf(e),src:'记忆档案·'+(e.category||'')+'·'+(e.priority||'normal'),text:plain(e.content,900)})})}catch(e){}
    try{(await A.all('memories')).forEach(function(m){if(!m||!A.memVisible(m,cfg.id))return;var t=tsOf(m);if(t<since)return;items.push({ts:t,src:'记忆库'+(m.domain?'·'+m.domain:''),text:plain((m.title?m.title+'：':'')+(m.content||m.summary||''),700)})})}catch(e){}
    try{(await A.all('calEvents')).forEach(function(ev){if(!ev||ev.aiHidden||ev.private)return;var t=Date.parse((ev.date||'')+(ev.time?' '+ev.time:'')||'')||tsOf(ev);if(!t||t<since||t>Date.now()+86400000)return;items.push({ts:t,src:'日历',text:plain((ev.date||'')+(ev.time?' '+ev.time:'')+' '+(ev.title||ev.name||'')+(ev.note?'：'+ev.note:''),300)})})}catch(e){}
    if(useSum){try{(await A.all('chatSummaries')).forEach(function(s){if(!s||s.friendId!==cfg.id)return;var t=tsOf(s);if(t<since)return;items.push({ts:t,src:'对话摘要'+(s.threadId?'·话题':''),text:plain(s.summary||s.text||'',1500)})})}catch(e){}}
    if(useBlog){var ok=false;try{ok=await A.blogAllowed(cfg)}catch(e){}
      if(!ok)note.push('这位 TA 没有日志阅读权限，日志没有带');
      else{try{(await A.all('posts')).forEach(function(p){if(!p||p.draft||A.locked(p))return;var t=tsOf(p)||Date.parse(p.date||'')||0;if(!t||t<since)return;items.push({ts:t,src:'日志'+(p.category?'·'+p.category:''),text:plain((p.title?'《'+p.title+'》':'')+(p.content||''),900)})})}catch(e){}}}
    items.sort(function(x,y){return x.ts-y.ts});
    var total=items.reduce(function(s,x){return s+x.text.length},0);
    while(total>MAXTOT&&items.length>1){var d=items.shift();total-=d.text.length;if(!note.some(function(n){return n.indexOf('太长')>=0}))note.push('材料太长，最早的部分没有带')}
    return {items:items,note:note,total:total,ctx:ctx}}
  function chunks(items,total){if(total==null)total=items.reduce(function(s,x){return s+x.text.length},0);if(total<=CHUNK)return items.length?[items]:[];var size=total>100000?SEG_BIG:SEG,out=[],cur=[],len=0;items.forEach(function(it){var l=it.text.length+40;if(len+l>size&&cur.length){out.push(cur);cur=[];len=0}cur.push(it);len+=l});if(cur.length)out.push(cur);return out}/* 一条材料（一条记忆 / 一篇日志 / 一段摘要）不拆开，事件不会被切在中间；一段宁可多几百字 */
  function fmt(items){return items.map(function(it){return '【'+it.src+' · '+dstr(it.ts)+'】'+it.text}).join('\n')}
  function parse(t,cat,prio){t=String(t||'').trim();if(!t)return null;var m=t.match(/<mem_create\b([^>]*)>([\s\S]*?)<\/mem_create\s*>/i);var body=m?m[2]:t,at=m?m[1]:'';
    if(/^[「"]?无新增/.test(body.trim()))return {none:true};
    var c=(at.match(/category="([^"]*)"/)||[])[1],p=(at.match(/priority="([^"]*)"/)||[])[1];
    body=body.replace(/^```[a-z]*\s*|\s*```$/g,'').trim();if(!m&&body.length>MAXLEN+200)return null;
    return {content:body.slice(0,MAXLEN),cat:cat,prio:prio,tagCat:c,tagPrio:p}}/* 类别与权重以用户在抽屉里选的为准，TA 标签里写的只作参考 */
  async function run(o,prog,ctl){
    ctl=ctl||{};var stopped=function(){return !!(ctl.stopped&&ctl.stopped())},halt=function(){if(stopped())throw new Error('已停止')};
    var cfg=A.cfg(o.cfgId);if(!cfg)throw new Error('没有这位 TA');
    var user=await A.userName(),ta=A.name(cfg),from=dstr(Date.now()-o.days*86400000),to=dstr(Date.now());
    prog({msg:'整理材料',step:0,steps:2});var g=await gather(cfg,o.days,o.useSum,o.useBlog,o.useCtx);halt();
    if(!g.items.length)return {none:true,note:g.note.concat(['这段时间里没有 '+ta+' 能看见的新材料'])};
    var cs=chunks(g.items,g.total),N=cs.length,LIMIT=limitOf(g.total,N);
    var base={TA:ta,USER:user,FROM:from,TO:to,CAT:o.cat,PRIO:o.prio,MAX:MAXLEN,N:N,LIMIT:LIMIT};
    var sys=fill(SYS_T+(CAT_T[o.cat]||CAT_T.personal_context)+OUT_T+(N>1?'\n\n'+FINAL_T:''),base),reply='';/* 不分段：通用基底 + 该类目的写法 + 输出规格；分段的第二阶段（铸型）再接第二阶段指令，素材卡片走 user 消息 */
    var tok={i:0,o:0,calls:0,real:false},steps=N===1?2:N+2;
    var raw=ctl.raw||(ctl.raw={});raw.total=g.total;raw.segs=N;raw.limit=LIMIT;raw.notes=[];raw.material=(g.ctx?g.ctx+'\n\n':'')+fmt(g.items);/* 压缩前的全部内容留给界面：分段分离出的素材卡片随段追加，原始材料整份 */
    var est=function(s,sy){return Math.round(((sy||sys).length+s.length)*0.8)};/* 发出前的估算（中文约 0.8 token / 字），API 回报后换成实际数 */
    var take=function(r){tok.calls++;if(r&&r.u){tok.i+=r.u.i||0;tok.o+=r.u.o||0;tok.real=true}return r};
    var report=function(msg,step,text,sy){prog({msg:msg,step:step,steps:steps,est:est(text,sy),tok:tok,total:g.total,segs:N})};
    var writeOnce=async function(text,label,step){report(label,step,text);var r=take(await A.call(cfg,sys,text,ctl));
      if(r.trunc&&!/<\/mem_create/i.test(r.t)){halt();report(label+' · 被截断，放宽长度重写',step,text);r=take(await A.call(cfg,sys,text,Object.assign({},ctl,{maxTokens:16384})))}/* 8192 不够写完（推理型号把思考也算进 max_tokens）时放宽一次 */
      return r.t};
    if(N===1)reply=await writeOnce((g.ctx?g.ctx+'\n\n':'')+'【材料】\n'+fmt(cs[0])+'\n\n请按上面的要求写这一条。','写条目',1);
    else{var notes=raw.notes;for(var i=0;i<N;i++){halt();var sys1=fill(SYS_T+STAGE_T,Object.assign({},base,{I:i+1})),ui='【材料 · 第 '+(i+1)+' / '+N+' 段】\n'+fmt(cs[i]);/* 第一阶段（分离）：system＝通用基底 + 第一阶段指令，不带类目写法与输出规格；本段材料走 user 消息；身份区块不带 */report('第 '+(i+1)+' / '+N+' 段 · 分离素材',1+i,ui,sys1);var r='';try{r=take(await A.call(cfg,sys1,ui,Object.assign({},ctl,{maxTokens:4096}))).t}catch(e){if(stopped())throw new Error('已停止');r=''}if(String(r).trim())notes.push('【第 '+(i+1)+' 段素材卡片】\n'+cards(r,Math.round(LIMIT*1.5)));else g.note.push('第 '+(i+1)+' 段没分离出素材卡片，已跳过')}
      if(!notes.length)throw new Error('每一段都没分离出素材卡片，换个 API 再试');halt();
      reply=await writeOnce((g.ctx?g.ctx+'\n\n':'')+'【素材卡片 · 来自 '+N+' 段材料】\n'+notes.join('\n\n')+'\n\n请按上面的要求写这一条。','合段 · 铸型写条目',1+N)}
    var p=parse(reply,o.cat,o.prio);if(!p)throw new Error('TA 没按格式回，原文：'+plain(reply,200));
    p.note=g.note;p.total=g.total;p.segs=N;p.tok=tok;p.raw=raw;return p}
  async function write(o){var cfg=A.cfg(o.cfgId);if(!cfg)throw new Error('没有这位 TA');var content=String(o.content||'').trim().slice(0,MAXLEN);if(!content)throw new Error('内容为空');
    if(o.prio==='always'){var ex=await A.amEntries(cfg.id);if(ex.filter(function(e){return e.priority==='always'}).length>=3)throw new Error('always 条目已达 3 条上限，先去档案里腾一条')}
    var entry={id:A.newId(),friendId:cfg.id,category:o.cat,priority:o.prio,content:content,created:Date.now(),updated:Date.now(),updatedBy:'记忆总结 · '+A.name(cfg)};await A.put('autoMemory',entry);try{A.refresh()}catch(e){}return entry}

  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  /* ── 进度与后台状态：S 是唯一真相，抽屉里的进度卡与顶栏小条都只是它的画面；抽屉关了也照跑 ── */
  var S={on:false,t0:0,t1:0,stepT:0,inf:null,res:null,err:null,ctl:null,seen:true,tab:'cards'},tick=null,last=null;
  function fmtT(ms){var s=Math.max(0,Math.round(ms/1000));return ('0'+Math.floor(s/60)).slice(-2)+':'+('0'+(s%60)).slice(-2)}
  function fmtK(n){n=Math.max(0,Math.round(n||0));return n>=1e6?(n/1e6).toFixed(2)+'M':n>=1000?(n/1000).toFixed(1)+'k':String(n)}
  function fmtN(n){return String(Math.max(0,Math.round(n||0))).replace(/\B(?=(\d{3})+(?!\d))/g,',')}
  function sheetOpen(){var sh=document.getElementById('sh-amsum');return !!(sh&&sh.classList.contains('open'))}
  function tokLine(inf,fin){var t=inf&&inf.tok,s='';if(t&&t.real)s='已用 '+fmtK(t.i+t.o)+' tokens · 输入 '+fmtK(t.i)+' / 输出 '+fmtK(t.o);if(!fin&&inf&&inf.est)s+=(s?' · ':'')+'这一步发出 ≈ '+fmtK(inf.est);if(!s&&!fin)s='API 回报后显示实际 token 数';return s}
  /* ── 压缩前的内容：自绘查看器，两枚页签（素材卡片 / 原始材料）+ 计数行 + pre-wrap 滚动块，不用 textarea ── */
  function rawInfo(){var raw=S.ctl&&S.ctl.raw;return (raw&&raw.material)?raw:null}
  function rawCards(){var raw=rawInfo();return (raw&&raw.notes&&raw.notes.length)?raw.notes.join('\n\n'):''}
  function rawMat(){var raw=rawInfo();return raw?raw.material:''}
  function rawPaint(){var box=$('as-rawbox');if(!box||box.hidden)return;var raw=rawInfo(),tabs=$('as-tabs'),multi=!!(raw&&raw.segs>1);tabs.hidden=!multi;if(!multi)S.tab='raw';
    Array.prototype.forEach.call(tabs.querySelectorAll('.chip'),function(c){c.classList.toggle('on',c.dataset.t===S.tab)});
    var t='',info='';
    if(S.tab==='cards'){t=rawCards();var n=raw?raw.notes.length:0;info=n?('已分离 '+n+' / '+raw.segs+' 段 · 共 '+fmtN(t.length)+' 字 · 每段上限 '+raw.limit+' 字 · 铸型成条目之前的素材'):'分段还没有完成任何一段'}
    else{t=rawMat();info=raw?('喂给 TA 的原始材料 · '+fmtN(raw.total)+' 字'+(raw.segs>1?' · 分 '+raw.segs+' 段':'')):''}
    $('as-rawm').textContent=info;var v=$('as-raw');v.textContent=t||'（空）';v.scrollTop=0}
  function copyRaw(){var t=S.tab==='cards'?rawCards():rawMat();if(!t)return;var done=function(){try{toast('已复制')}catch(e){}};
    var fb=function(){try{var ta=document.createElement('textarea');ta.value=t;ta.setAttribute('readonly','');ta.style.cssText='position:fixed;left:-9999px;top:0;opacity:0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();done()}catch(e){}};
    try{navigator.clipboard.writeText(t).then(done,fb)}catch(e){fb()}}
  function paint(){var pc=$('as-prog');if(!pc)return;var inf=S.inf||{},run=S.on,show=run||!!S.res||!!S.err;pc.hidden=!show;
    if(show){var n=Math.max(1,Math.min(24,inf.steps||1)),cur=Math.min(n,inf.step||0),done=run||S.err?cur:n;pc.classList.toggle('run',run);pc.classList.toggle('err',!!S.err);
      var bar=$('as-pb');if(bar.childElementCount!==n)bar.innerHTML=new Array(n+1).join('<i></i>');for(var k=0;k<n;k++)bar.children[k].className=k<done?'d':(run&&k===done?'c':'');/* 分段轨道：步数几段就几格，已完成实填、进行中扫光、待做空格 */
      var mat=inf.total?('材料 '+fmtN(inf.total)+' 字'+(inf.segs>1?' · 分 '+inf.segs+' 段':'')):'';
      if(run){$('as-pl').textContent=inf.msg||'…';$('as-pm1').textContent='第 '+Math.min(n,cur+1)+' / '+n+' 步'+(mat?' · '+mat:'');$('as-pm2').textContent=tokLine(inf,false);$('as-pt').textContent=(Date.now()-(S.stepT||S.t0)>60000)?'这一步等得久，多半是推理型号在想。切到别的页面也会继续；切出 APP 或锁屏不保证。':'切到别的页面也会继续，写好后回来看；切出 APP 或锁屏不保证。'}
      else if(S.err){$('as-pl').textContent=S.err;$('as-pm1').textContent='停在第 '+Math.min(n,cur+1)+' / '+n+' 步'+(mat?' · '+mat:'');$('as-pm2').textContent=tokLine(S.inf,true);$('as-pt').textContent=''}
      else{var r=S.res,tk=r.tok;$('as-pl').textContent=r.none?'TA 说这段时间没有值得新记的':'写好了';$('as-pm1').textContent='材料 '+fmtN(r.total||0)+' 字'+(r.segs>1?' · 分 '+r.segs+' 段':'')+(tk?' · '+tk.calls+' 次调用':'');$('as-pm2').textContent=(tk&&tk.real)?('共 '+fmtK(tk.i+tk.o)+' tokens · 输入 '+fmtK(tk.i)+' / 输出 '+fmtK(tk.o)):'';$('as-pt').textContent=r.none?(r.note||[]).join('；'):('看一眼，可以改，满意再写入。'+((r.note||[]).length?' '+(r.note||[]).join('；'):''))}
      $('as-pe').textContent=fmtT((run?Date.now():S.t1)-S.t0)}
    var rt=$('as-rawt');if(rt){var has=!S.on&&!!rawInfo();rt.hidden=!has;if(!has){$('as-rawbox').hidden=true;rt.textContent='看压缩前的全部内容'}}
    var pill=$('as-pill');if(pill){var pv=(run||((S.res||S.err)&&!S.seen))&&!sheetOpen();pill.classList.toggle('show',pv);
      if(pv){$('as-pill-t').textContent=run?('记忆总结 · '+(inf.msg||'…')+' · '+fmtT(Date.now()-S.t0)):(S.err?'记忆总结 · 出错，点开看':'记忆总结 · 写好了，点开看');pill.classList.toggle('done',!run);var C=2*Math.PI*9,f=run?((inf.step||0)/(inf.steps||1)):1;$('as-pill-r').setAttribute('stroke-dashoffset',(C*(1-f)).toFixed(1));$('as-pill-x').textContent=run?'✕':'✓';$('as-pill-x').setAttribute('aria-label',run?'停止':'知道了')}}
    var go=$('as-go');if(go){go.textContent=run?'停止':'开始总结';go.classList.toggle('as-stop',run);go.disabled=false}}
  function idle(){if(!S.on&&S.seen&&tick){clearInterval(tick);tick=null}}
  async function start(o){if(S.on)return;var stop=false,ac=null;try{ac=new AbortController()}catch(e){}
    S.on=true;S.t0=Date.now();S.t1=0;S.stepT=Date.now();S.inf=null;S.res=null;S.err=null;S.seen=false;S.tab='cards';last=null;
    S.ctl={signal:ac?ac.signal:null,stopped:function(){return stop},stop:function(){if(stop)return;stop=true;try{ac&&ac.abort()}catch(e){}}};
    $('as-save').hidden=true;$('as-out').hidden=true;$('as-note').textContent='';var rb0=$('as-rawbox');if(rb0)rb0.hidden=true;
    if(tick)clearInterval(tick);tick=setInterval(paint,500);paint();
    try{var p=await run(o,function(inf){if(!S.inf||S.inf.step!==inf.step)S.stepT=Date.now();S.inf=inf;paint()},S.ctl);
      S.res=p;if(!p.none){last=Object.assign({},o,{cat:p.cat,prio:p.prio});$('as-txt').value=p.content;$('as-out').hidden=false;$('as-save').hidden=false;$('as-note').textContent=(p.note||[]).join('；')}}
    catch(e){S.err=(stop?'已停止':'出错：'+String((e&&e.message)||e))}
    finally{S.on=false;S.t1=Date.now();S.seen=sheetOpen();paint();idle()}}
  var CSS='#sh-amsum [hidden]{display:none!important}'+'#sh-amsum .as-row{display:flex;gap:8px}#sh-amsum .as-row .f-group{flex:1;min-width:0}#sh-amsum .as-note{font-size:.74rem;color:var(--tx3);line-height:1.6;margin-top:6px}#sh-amsum textarea{width:100%;min-height:150px;box-sizing:border-box;resize:none}#sh-amsum .as-chk{display:flex;align-items:center;gap:8px;font-size:.84rem;color:var(--tx2);padding:6px 0}#sh-amsum .as-chk .sw2{margin-left:auto}#sh-amsum .as-btns{display:flex;gap:8px;margin-top:10px}#sh-amsum .as-btns .btn{flex:1}#sh-amsum .btn.as-stop{color:#c98899;border-color:rgba(201,136,153,.55)}'
    +'#sh-amsum .as-prog{margin:10px 0 4px;padding:12px 14px 11px;border-radius:14px;border:1px solid color-mix(in srgb,var(--line) 85%,transparent);background:color-mix(in srgb,var(--soft) 55%,transparent)}#sh-amsum .as-ph{display:flex;align-items:baseline;gap:10px}#sh-amsum .as-pl{flex:1;min-width:0;font-size:.84rem;color:var(--tx);line-height:1.5;word-break:break-all}#sh-amsum .as-pl::before{content:"";display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--acc);margin:0 7px 2px 0;vertical-align:middle;opacity:.55}#sh-amsum .as-prog.run .as-pl::before{opacity:1;animation:asBreath 2.2s ease-in-out infinite}#sh-amsum .as-prog.err .as-pl{color:#c98899}#sh-amsum .as-prog.err .as-pl::before{background:#c98899;animation:none}@keyframes asBreath{0%,100%{opacity:.35;transform:scale(.8)}50%{opacity:1;transform:scale(1)}}body.ib-reduce #sh-amsum .as-pl::before{animation:none}#sh-amsum .as-pe{flex:none;font-family:var(--serif);font-weight:600;font-size:1.04rem;color:var(--tx);font-variant-numeric:tabular-nums;letter-spacing:.04em}'
    +'#sh-amsum .as-bar{display:flex;gap:3px;height:5px;margin:9px 0 8px}#sh-amsum .as-bar i{flex:1;min-width:0;position:relative;border-radius:3px;background:var(--soft);overflow:hidden;transition:background .4s ease}#sh-amsum .as-bar i.d{background:linear-gradient(90deg,color-mix(in srgb,var(--acc) 55%,white),var(--acc))}#sh-amsum .as-bar i.c{background:color-mix(in srgb,var(--acc) 22%,transparent)}#sh-amsum .as-bar i.c::after{content:"";position:absolute;top:0;bottom:0;width:60%;left:-70%;border-radius:3px;background:linear-gradient(90deg,transparent,color-mix(in srgb,var(--acc) 70%,white),transparent);animation:asSheen 1.4s ease-in-out infinite}@keyframes asSheen{to{left:110%}}body.ib-reduce #sh-amsum .as-bar i.c::after{display:none}'
    +'#sh-amsum .as-pm{font-size:.74rem;color:var(--tx2);line-height:1.6;font-variant-numeric:tabular-nums}#sh-amsum .as-pm span{display:block;min-width:0}#sh-amsum .as-pm .as-pm2:empty{display:none}#sh-amsum .as-pt{font-size:.7rem;color:var(--tx3);line-height:1.6;margin-top:2px}#sh-amsum .as-rawt{display:block;margin:8px 0 0;padding:4px 0;font-size:.76rem;color:var(--acc);background:none;border:none;cursor:pointer;font-family:inherit}'
    +'#sh-amsum .as-rawbox{margin-top:6px}#sh-amsum .as-rawh{display:flex;align-items:center;gap:8px;margin:2px 0 8px}#sh-amsum .as-tabs{flex:1;min-width:0;gap:6px}#sh-amsum .as-tabs[hidden]{display:none}#sh-amsum .as-tabs .chip{padding:5px 12px;font-family:inherit;line-height:1.3}#sh-amsum .as-rawc{flex:none;margin-left:auto;padding:4px 12px;border-radius:999px;border:1px solid var(--glass-line);background:none;color:var(--tx2);font-size:.72rem;font-family:inherit}#sh-amsum .as-rawm{font-size:.7rem;color:var(--tx3);line-height:1.6;margin:0 0 6px}#sh-amsum .as-rawv{min-height:120px;max-height:40vh;overflow-y:auto;padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--soft);font-size:.76rem;line-height:1.65;color:var(--tx2);white-space:pre-wrap;word-break:break-word;-webkit-user-select:text;user-select:text}'
    +'#as-pill{position:fixed;right:14px;top:calc(8px + 50px*var(--szTop,1) + var(--sat,0px) + 8px);z-index:40;display:none;align-items:center;gap:8px;max-width:calc(100vw - 28px);padding:6px 8px 6px 9px;border-radius:999px;border:1px solid var(--glass-line);background:var(--sheet);backdrop-filter:blur(18px) saturate(1.3);-webkit-backdrop-filter:blur(18px) saturate(1.3);box-shadow:0 6px 22px rgba(40,70,120,.14);cursor:pointer}#as-pill.show{display:flex}body.ib-reduce #as-pill{backdrop-filter:none;-webkit-backdrop-filter:none}'
    +'#as-pill svg{width:20px;height:20px;transform:rotate(-90deg);flex:none}#as-pill circle{fill:none;stroke-width:2.6;stroke-linecap:round}#as-pill circle.bg{stroke:var(--soft)}#as-pill circle.v{stroke:var(--acc);transition:stroke-dashoffset .5s}#as-pill.done circle.v{filter:drop-shadow(0 0 4px var(--acc))}#as-pill span{font-size:.74rem;color:var(--tx);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-variant-numeric:tabular-nums}#as-pill button{flex:none;width:22px;height:22px;border-radius:50%;border:1px solid var(--glass-line);background:none;color:var(--tx2);font-size:.68rem;display:flex;align-items:center;justify-content:center;padding:0}';
  function build(){if(document.getElementById('sh-amsum'))return;var st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);
    var sh=document.createElement('div');sh.className='sheet';sh.id='sh-amsum';
    sh.innerHTML='<h3 class="sheet-t">记忆总结</h3>'
      +'<div class="f-group"><label>谁来总结 <span class="lb-note">（用 TA 本人的 API，只看 TA 能看见的）</span></label><div class="sel"><select id="as-cfg"></select></div></div>'
      +'<div class="as-row"><div class="f-group"><label>时间范围</label><div class="sel"><select id="as-days"><option value="7">最近一周</option><option value="30" selected>最近一个月</option><option value="90">最近三个月</option><option value="180">最近半年</option><option value="365">最近一年</option></select></div></div>'
      +'<div class="f-group"><label>写成哪一类</label><div class="sel"><select id="as-cat"></select></div></div></div>'
      +'<div class="as-row"><div class="f-group"><label>权重</label><div class="sel"><select id="as-prio"><option value="normal" selected>normal</option><option value="low">low</option><option value="always">always（至多 3 条）</option></select></div></div></div>'
      +'<div class="as-chk">带上提示词与关系信息（人设、关系、你的昵称与简介）<span class="sw2 on" id="as-ctx"></span></div><div class="as-chk">带上对话摘要<span class="sw2 on" id="as-sum"></span></div><div class="as-chk">带上这段时间的日志（TA 要有日志权限）<span class="sw2" id="as-blog"></span></div>'
      +'<div class="as-prog" id="as-prog" hidden><div class="as-ph"><span class="as-pl" id="as-pl"></span><span class="as-pe" id="as-pe">00:00</span></div><div class="as-bar" id="as-pb"></div><div class="as-pm"><span id="as-pm1"></span><span class="as-pm2" id="as-pm2"></span></div><div class="as-pt" id="as-pt"></div></div>'
      +'<div class="f-group" id="as-out" hidden><label>TA 写的条目 <span class="lb-note">（可改，上限 1500 字）</span></label><textarea id="as-txt" maxlength="1500" rows="6"></textarea><div class="as-note" id="as-note"></div></div>'
      +'<button class="as-rawt" id="as-rawt" hidden>看压缩前的全部内容</button><div class="as-rawbox" id="as-rawbox" hidden><div class="as-rawh"><div class="chips as-tabs" id="as-tabs"><button type="button" class="chip on" data-t="cards">素材卡片</button><button type="button" class="chip" data-t="raw">原始材料</button></div><button class="as-rawc" id="as-rawc" type="button">复制</button></div><div class="as-rawm" id="as-rawm"></div><div class="as-rawv" id="as-raw"></div></div>'
      +'<div class="as-btns"><button class="btn wide primary" id="as-go">开始总结</button><button class="btn wide" id="as-save" hidden>写入档案</button></div>';
    document.body.appendChild(sh);
    var pill=document.createElement('div');pill.id='as-pill';pill.setAttribute('role','button');pill.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle class="bg" cx="12" cy="12" r="9"/><circle class="v" id="as-pill-r" cx="12" cy="12" r="9" stroke-dasharray="56.5" stroke-dashoffset="56.5"/></svg><span id="as-pill-t"></span><button id="as-pill-x" aria-label="停止">✕</button>';document.body.appendChild(pill);
    pill.addEventListener('click',function(e){if(e.target.closest('#as-pill-x')){if(S.on&&S.ctl)S.ctl.stop();else{S.seen=true;paint();idle()}return}open()});
    var cat=$('as-cat');cat.innerHTML=Object.keys(A.cats()).map(function(k){return '<option value="'+esc(k)+'"'+(k==='top_of_mind'?' selected':'')+'>'+esc(k)+(A.cats()[k]&&A.cats()[k]!==k?' · '+esc(A.cats()[k]):'')+'</option>'}).join('');
    ['as-ctx','as-sum','as-blog'].forEach(function(id){$(id).addEventListener('click',function(){$(id).classList.toggle('on')})});
    $('as-go').addEventListener('click',function(){if(S.on){if(S.ctl)S.ctl.stop();return}var cs=$('as-cfg');var o={cfgId:cs.value,days:parseInt($('as-days').value,10)||30,cat:cat.value,prio:$('as-prio').value,useCtx:$('as-ctx').classList.contains('on'),useSum:$('as-sum').classList.contains('on'),useBlog:$('as-blog').classList.contains('on')};
      if(!o.cfgId){toast('先到 API 页添加一位 TA');return}start(o)});
    $('as-rawt').addEventListener('click',function(){var b=$('as-rawbox');var opening=b.hidden;b.hidden=!opening;$('as-rawt').textContent=opening?'收起压缩前的内容':'看压缩前的全部内容';if(opening)rawPaint()});
    $('as-tabs').addEventListener('click',function(e){var c=e.target.closest('.chip');if(!c)return;S.tab=c.dataset.t;rawPaint()});$('as-rawc').addEventListener('click',copyRaw);
    $('as-save').addEventListener('click',async function(){if(!last)return;var b=$('as-save');b.disabled=true;try{last.content=$('as-txt').value;last.cat=cat.value;last.prio=$('as-prio').value;await write(last);toast('已写入 '+A.name(A.cfg(last.cfgId))+' 的记忆档案');$('as-save').hidden=true;$('as-out').hidden=true;$('as-pl').textContent='已写入档案。';$('as-pt').textContent='';last=null}catch(e){toast(String((e&&e.message)||e))}finally{b.disabled=false}})}
  function open(){build();var cs=$('as-cfg'),keep=cs.value;cs.innerHTML=A.cfgs().map(function(c){return '<option value="'+esc(c.id)+'">'+esc(A.name(c))+'</option>'}).join('')||'<option value="">先到 API 页添加 TA</option>';if(keep&&Array.prototype.some.call(cs.options,function(op){return op.value===keep}))cs.value=keep;/* 重开抽屉不再把「谁来总结」重置回第一位 */openSheet('sh-amsum');S.seen=true;paint();idle()}
  function boot(){var b=$('mem-add');if(b&&!document.getElementById('mem-sum')){var row=document.createElement('div');row.style.cssText='display:flex;gap:8px;margin-bottom:12px';b.style.marginBottom='0';b.parentNode.insertBefore(row,b);row.appendChild(b);var s=document.createElement('button');s.className='btn wide';s.id='mem-sum';s.textContent='记忆总结';s.addEventListener('click',open);row.appendChild(s)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,0)});else setTimeout(boot,0);
  window.IBAmSum={open:open,run:run,write:write,gather:gather,chunks:chunks,parse:parse,state:S,stop:function(){if(S.on&&S.ctl)S.ctl.stop()},SYS:SYS_T,STAGE:STAGE_T,FINAL:FINAL_T};
})();
