
(function(){var st=document.createElement('style');st.id='ib-fx-css';st.textContent='body.ib-fx-mid,body.ib-fx-mid *{text-shadow:none!important}body.ib-fx-mid .m{box-shadow:none!important;-webkit-backdrop-filter:none!important;backdrop-filter:none!important}body.ib-fx-mid:not(.theme-infernal) .m.ai{background:rgba(247,251,255,0.88)}body.ib-fx-mid:not(.theme-infernal) .m.user{background:rgba(214,229,247,0.9)}body.ib-fx-mid.theme-infernal .m.ai{background:rgba(38,50,78,0.88)}body.ib-fx-mid.theme-infernal .m.user{background:rgba(54,86,134,0.88)}body.ib-fx-mid .vm-stack .vmsg,body.ib-fx-mid .vm-stack .ibvb{-webkit-backdrop-filter:none;backdrop-filter:none}body.ib-fx-mid:not(.theme-infernal) .vm-stack.user .vmsg,body.ib-fx-mid:not(.theme-infernal) .vm-stack.user .ibvb{background:#dbe7f8}body.ib-fx-mid.theme-infernal .vm-stack.user .vmsg,body.ib-fx-mid.theme-infernal .vm-stack.user .ibvb{background:#223657}body.ib-fx-mid:not(.theme-infernal) .vm-stack.ai .vmsg,body.ib-fx-mid:not(.theme-infernal) .vm-stack.ai .ibvb{background:#f2f7fd}body.ib-fx-mid.theme-infernal .vm-stack.ai .vmsg,body.ib-fx-mid.theme-infernal .vm-stack.ai .ibvb{background:#202b41}body.ib-fx-mid .mrow{content-visibility:auto;contain-intrinsic-size:64px;contain-intrinsic-size:auto 64px}';document.head.appendChild(st);
function mp9(){return (typeof _mp!=='undefined'&&_mp)?_mp:null}
function cur(){var m=mp9();if(m&&m.ui&&m.ui.reduce)return 'low';var f='';try{f=(m&&m.ui&&m.ui.fx)||localStorage.getItem('ib_fx')||''}catch(e){}return f==='mid'?'mid':'high'}
function apply(){var m=mp9();var mid=!!(m&&m.ui&&m.ui.fx==='mid'&&!m.ui.reduce);document.body.classList.toggle('ib-fx-mid',mid);try{localStorage.setItem('ib_fx',mid?'mid':'')}catch(e){}var sel=document.getElementById('ui-fx');if(sel)sel.value=cur()}
async function set(v){var m=mp9();if(!m)return;m.ui=m.ui||{};if(v==='low'){m.ui.reduce=true;m.ui.fx=''}else{m.ui.reduce=false;m.ui.fx=(v==='mid'?'mid':'')}try{localStorage.setItem('ib_reduce',m.ui.reduce?'1':'0')}catch(e){}document.body.classList.toggle('ib-reduce',!!m.ui.reduce);try{var sw=document.getElementById('ui-reduce');if(sw&&typeof sw2==='function')sw2(sw,!!m.ui.reduce)}catch(e){}try{if(typeof saveMP==='function')await saveMP()}catch(e){}apply();try{if(typeof _uiApply==='function')_uiApply()}catch(e){}try{if(typeof toast==='function')toast('特效质量：'+(v==='low'?'低':v==='mid'?'中':'高'))}catch(e){}}
function boot(){(async function(){try{if(typeof loadMP==='function')await loadMP()}catch(e){}apply();var sel=document.getElementById('ui-fx');if(sel&&!sel._fx){sel._fx=1;sel.addEventListener('change',function(){set(sel.value)})}
  try{if(typeof _uiApply==='function'){var _o=_uiApply;_uiApply=async function(){var r=await _o.apply(this,arguments);try{apply()}catch(e){}return r}}}catch(e){}
  try{if(typeof SEC_RENDER!=='undefined'&&SEC_RENDER){var o9=SEC_RENDER['visual:main'];SEC_RENDER['visual:main']=function(){try{if(o9)o9.apply(this,arguments)}catch(e){}apply()}}}catch(e){}
  var sw=document.getElementById('ui-reduce');if(sw)sw.addEventListener('click',function(){setTimeout(apply,60)})})()}
window.IBFx={apply:apply,set:set,cur:cur};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0)})();
